// Primary Science Questions
// Initial batch of questions migrated to modular ChallengeQuestion format

import type { ChallengeQuestion } from '../types';

export const primaryScienceQuestions: ChallengeQuestion[] = [
  // ============================================
  // MCQ Questions (Initial Batch)
  // ============================================

  // Primary Science - Animals
  {
    id: 'primary-sci-001',
    type: 'mcq',
    question: 'Which animal lives on land?',
    options: ['Fish', 'Bird', 'Dog', 'Shark'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Animals',
    explanation: 'Dogs live on land',
    source: 'practice',
  },
  {
    id: 'primary-sci-002',
    type: 'mcq',
    question: 'How many legs does a cat have?',
    options: ['2', '3', '4', '6'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Animals',
    explanation: 'A cat has 4 legs',
    source: 'practice',
  },
  {
    id: 'primary-sci-003',
    type: 'mcq',
    question: 'Which animal can swim?',
    options: ['Dog', 'Fish', 'Bird', 'Cat'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Animals',
    explanation: 'Fish can swim',
    source: 'practice',
  },
  {
    id: 'primary-sci-004',
    type: 'mcq',
    question: 'Which animal can fly?',
    options: ['Fish', 'Bird', 'Dog', 'Cat'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Animals',
    explanation: 'Birds can fly',
    source: 'practice',
  },
  {
    id: 'primary-sci-005',
    type: 'mcq',
    question: 'How many legs does a dog have?',
    options: ['2', '3', '4', '6'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Animals',
    explanation: 'A dog has 4 legs',
    source: 'practice',
  },

  // Primary Science - Body Parts
  {
    id: 'primary-sci-006',
    type: 'mcq',
    question: 'What do we use to see?',
    options: ['Ears', 'Eyes', 'Nose', 'Mouth'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Body Parts',
    explanation: 'We use our eyes to see',
    source: 'practice',
  },
  {
    id: 'primary-sci-007',
    type: 'mcq',
    question: 'What do we use to hear?',
    options: ['Eyes', 'Ears', 'Nose', 'Mouth'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Body Parts',
    explanation: 'We use our ears to hear',
    source: 'practice',
  },
  {
    id: 'primary-sci-008',
    type: 'mcq',
    question: 'What do we use to smell?',
    options: ['Eyes', 'Ears', 'Nose', 'Mouth'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Body Parts',
    explanation: 'We use our nose to smell',
    source: 'practice',
  },

  // Primary Science - Plants
  {
    id: 'primary-sci-009',
    type: 'mcq',
    question: 'What do plants need to make food?',
    options: ['Water only', 'Sunlight only', 'Water and sunlight', 'Nothing'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Plants',
    explanation: 'Plants need both water and sunlight to make food',
    source: 'practice',
  },
  {
    id: 'primary-sci-010',
    type: 'mcq',
    question: 'What do plants grow from?',
    options: ['Rocks', 'Seeds', 'Water', 'Air'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Plants',
    explanation: 'Plants grow from seeds',
    source: 'practice',
  },

  // ============================================
  // Primary 1 - Five Senses & Body Parts
  // ============================================
  {
    id: 'primary-sci-011',
    type: 'mcq',
    question: 'How many senses do we have?',
    options: ['3', '4', '5', '6'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Five Senses',
    explanation: 'We have 5 senses: sight, hearing, smell, taste, and touch',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-012',
    type: 'mcq',
    question: 'What do we use to taste food?',
    options: ['Eyes', 'Ears', 'Nose', 'Tongue'],
    correctAnswer: 3,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Five Senses',
    explanation: 'We use our tongue to taste food',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-013',
    type: 'mcq',
    question: 'What do we use to touch things?',
    options: ['Eyes', 'Hands', 'Ears', 'Nose'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Five Senses',
    explanation: 'We use our hands (skin) to touch things',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-014',
    type: 'mcq',
    question: 'How many fingers do we have on one hand?',
    options: ['4', '5', '6', '10'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Body Parts',
    explanation: 'We have 5 fingers on one hand',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-015',
    type: 'mcq',
    question: 'What do we use to walk?',
    options: ['Hands', 'Legs', 'Eyes', 'Ears'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Body Parts',
    explanation: 'We use our legs to walk',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-016',
    type: 'mcq',
    question: 'Which animal has feathers?',
    options: ['Dog', 'Cat', 'Bird', 'Fish'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Animals',
    explanation: 'Birds have feathers',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-017',
    type: 'mcq',
    question: 'Which animal has fur?',
    options: ['Fish', 'Bird', 'Dog', 'Snake'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Animals',
    explanation: 'Dogs have fur',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-018',
    type: 'mcq',
    question: 'What color are most leaves?',
    options: ['Red', 'Blue', 'Green', 'Yellow'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Plants',
    explanation: 'Most leaves are green',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-019',
    type: 'mcq',
    question: 'What do we need to breathe?',
    options: ['Food', 'Water', 'Air', 'Sunlight'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Body Parts',
    explanation: 'We need air to breathe',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-020',
    type: 'mcq',
    question: 'Which part of the plant is under the ground?',
    options: ['Leaves', 'Flowers', 'Roots', 'Stem'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Plants',
    explanation: 'Roots are the part of the plant under the ground',
    source: 'practice',
    year: 2023,
  },

  // ============================================
  // Primary 2 - Living Things & Habitats
  // ============================================
  {
    id: 'primary-sci-021',
    type: 'mcq',
    question: 'Which is a living thing?',
    options: ['Rock', 'Tree', 'Water', 'Stone'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Living Things',
    explanation: 'A tree is a living thing (it grows and needs water)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-022',
    type: 'mcq',
    question: 'Which is a non-living thing?',
    options: ['Dog', 'Cat', 'Book', 'Bird'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Living Things',
    explanation: 'A book is a non-living thing',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-023',
    type: 'mcq',
    question: 'Where do fish live?',
    options: ['On land', 'In water', 'In the air', 'Underground'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Habitats',
    explanation: 'Fish live in water',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-024',
    type: 'mcq',
    question: 'Where do birds build their homes?',
    options: ['In water', 'In trees', 'Underground', 'In rocks'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Habitats',
    explanation: 'Birds build their nests in trees',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-025',
    type: 'mcq',
    question: 'What do animals need to live?',
    options: ['Food and water', 'Only food', 'Only water', 'Nothing'],
    correctAnswer: 0,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Living Things',
    explanation: 'Animals need both food and water to live',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-026',
    type: 'mcq',
    question: 'What season comes after rainy season in Ghana?',
    options: ['Dry season', 'Winter', 'Spring', 'Summer'],
    correctAnswer: 0,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Weather',
    explanation: 'After rainy season comes dry season in Ghana',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-027',
    type: 'mcq',
    question: 'What should we do to stay healthy?',
    options: ['Eat junk food only', 'Wash our hands', 'Never exercise', 'Stay dirty'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Health',
    explanation: 'We should wash our hands to stay healthy',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-028',
    type: 'mcq',
    question: 'How many legs does a spider have?',
    options: ['4', '6', '8', '10'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Animals',
    explanation: 'A spider has 8 legs',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-029',
    type: 'mcq',
    question: 'Which animal gives us milk?',
    options: ['Chicken', 'Cow', 'Fish', 'Bird'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Animals',
    explanation: 'Cows give us milk',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-030',
    type: 'mcq',
    question: 'What do plants need to grow?',
    options: ['Only water', 'Water, sunlight, and soil', 'Only sunlight', 'Nothing'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Plants',
    explanation: 'Plants need water, sunlight, and soil to grow',
    source: 'practice',
    year: 2023,
  },

  // ============================================
  // Primary 3 - Food Groups & Materials
  // ============================================
  {
    id: 'primary-sci-031',
    type: 'mcq',
    question: 'Which food group helps us grow strong?',
    options: ['Sweets', 'Proteins', 'Candy', 'Soda'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Food Groups',
    explanation: 'Proteins (like meat, beans) help us grow strong',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-032',
    type: 'mcq',
    question: 'Which food gives us energy?',
    options: ['Water', 'Carbohydrates', 'Rocks', 'Stones'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Food Groups',
    explanation: 'Carbohydrates (like rice, bread) give us energy',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-033',
    type: 'mcq',
    question: 'What happens to water when it gets very cold?',
    options: ['It becomes ice', 'It disappears', 'It becomes hot', 'Nothing'],
    correctAnswer: 0,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'States of Matter',
    explanation: 'Water becomes ice when it gets very cold (freezes)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-034',
    type: 'mcq',
    question: 'What happens to water when it gets very hot?',
    options: ['It becomes ice', 'It becomes steam', 'It disappears', 'Nothing'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'States of Matter',
    explanation: 'Water becomes steam when it gets very hot (boils)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-035',
    type: 'mcq',
    question: 'Which material is hard?',
    options: ['Water', 'Air', 'Rock', 'Steam'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Materials',
    explanation: 'Rock is a hard material',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-036',
    type: 'mcq',
    question: 'Which material can we see through?',
    options: ['Wood', 'Metal', 'Glass', 'Stone'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Materials',
    explanation: 'Glass is transparent - we can see through it',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-037',
    type: 'mcq',
    question: 'What do we call the process where plants make food?',
    options: ['Respiration', 'Photosynthesis', 'Digestion', 'Circulation'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Plants',
    explanation: 'Photosynthesis is the process where plants make food using sunlight',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-038',
    type: 'mcq',
    question: 'How many bones do adults have?',
    options: ['100', '150', '200', '206'],
    correctAnswer: 3,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Body Parts',
    explanation: 'Adults have 206 bones in their body',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-039',
    type: 'mcq',
    question: 'Which part of the body pumps blood?',
    options: ['Lungs', 'Heart', 'Brain', 'Stomach'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Body Parts',
    explanation: 'The heart pumps blood throughout the body',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-040',
    type: 'mcq',
    question: 'What do we call the hard outer covering of a tree?',
    options: ['Leaves', 'Bark', 'Roots', 'Flowers'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Plants',
    explanation: 'Bark is the hard outer covering of a tree',
    source: 'practice',
    year: 2023,
  },

  // ============================================
  // Primary 4 - Energy & Environment
  // ============================================
  {
    id: 'primary-sci-041',
    type: 'mcq',
    question: 'What is the main source of light on Earth?',
    options: ['Moon', 'Stars', 'Sun', 'Lamp'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Energy',
    explanation: 'The Sun is the main source of light on Earth',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-042',
    type: 'mcq',
    question: 'What do we call energy from the sun?',
    options: ['Solar energy', 'Wind energy', 'Water energy', 'Fire energy'],
    correctAnswer: 0,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Energy',
    explanation: 'Solar energy is energy from the sun',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-043',
    type: 'mcq',
    question: 'What should we do with waste to protect the environment?',
    options: ['Throw it anywhere', 'Burn it all', 'Recycle it', 'Leave it on the ground'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Environment',
    explanation: 'We should recycle waste to protect the environment',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-044',
    type: 'mcq',
    question: 'What do we call the three states of matter?',
    options: ['Solid, liquid, gas', 'Hot, cold, warm', 'Big, small, medium', 'Hard, soft, smooth'],
    correctAnswer: 0,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'States of Matter',
    explanation: 'The three states of matter are solid, liquid, and gas',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-045',
    type: 'mcq',
    question: 'Which is a solid?',
    options: ['Water', 'Air', 'Ice', 'Steam'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'States of Matter',
    explanation: 'Ice is a solid (frozen water)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-046',
    type: 'mcq',
    question: 'Which is a gas?',
    options: ['Water', 'Ice', 'Air', 'Rock'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'States of Matter',
    explanation: 'Air is a gas',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-047',
    type: 'mcq',
    question: 'What do we call animals that eat only plants?',
    options: ['Carnivores', 'Herbivores', 'Omnivores', 'Predators'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Animals',
    explanation: 'Herbivores are animals that eat only plants',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-048',
    type: 'mcq',
    question: 'What do we call animals that eat only meat?',
    options: ['Herbivores', 'Carnivores', 'Omnivores', 'Prey'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Animals',
    explanation: 'Carnivores are animals that eat only meat',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-049',
    type: 'mcq',
    question: 'What do we call the process where water changes to vapor?',
    options: ['Freezing', 'Melting', 'Evaporation', 'Condensation'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Water Cycle',
    explanation: 'Evaporation is when water changes to vapor (gas)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-050',
    type: 'mcq',
    question: 'What do we call rain, snow, and hail?',
    options: ['Evaporation', 'Condensation', 'Precipitation', 'Transpiration'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Water Cycle',
    explanation: 'Precipitation is rain, snow, and hail falling from clouds',
    source: 'practice',
    year: 2023,
  },

  // ============================================
  // Primary 5 - Solar System & Ecosystems
  // ============================================
  {
    id: 'primary-sci-051',
    type: 'mcq',
    question: 'What is the name of our planet?',
    options: ['Mars', 'Venus', 'Earth', 'Jupiter'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Solar System',
    explanation: 'Earth is the name of our planet',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-052',
    type: 'mcq',
    question: 'What is the closest star to Earth?',
    options: ['Moon', 'Sun', 'Mars', 'Venus'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Solar System',
    explanation: 'The Sun is the closest star to Earth',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-053',
    type: 'mcq',
    question: 'How many planets are in our solar system?',
    options: ['7', '8', '9', '10'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Solar System',
    explanation: 'There are 8 planets in our solar system',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-054',
    type: 'mcq',
    question: 'What do we call the path Earth takes around the Sun?',
    options: ['Rotation', 'Revolution', 'Orbit', 'Spin'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Solar System',
    explanation: 'Orbit is the path Earth takes around the Sun',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-055',
    type: 'mcq',
    question: 'What do we call all living and non-living things in an area?',
    options: ['Habitat', 'Ecosystem', 'Environment', 'Community'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Ecosystems',
    explanation: 'An ecosystem includes all living and non-living things in an area',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-056',
    type: 'mcq',
    question: 'What do we call the system that helps us breathe?',
    options: ['Digestive system', 'Respiratory system', 'Circulatory system', 'Nervous system'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Human Body',
    explanation: 'The respiratory system helps us breathe',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-057',
    type: 'mcq',
    question: 'What do we call the system that helps us digest food?',
    options: ['Respiratory system', 'Digestive system', 'Circulatory system', 'Nervous system'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Human Body',
    explanation: 'The digestive system helps us digest food',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-058',
    type: 'mcq',
    question: 'What force pulls objects toward Earth?',
    options: ['Magnetism', 'Gravity', 'Friction', 'Electricity'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Forces',
    explanation: 'Gravity is the force that pulls objects toward Earth',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-059',
    type: 'mcq',
    question: 'What do we call the process where plants release water?',
    options: ['Photosynthesis', 'Respiration', 'Transpiration', 'Evaporation'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Plants',
    explanation: 'Transpiration is when plants release water through their leaves',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-060',
    type: 'mcq',
    question: 'What do we call animals that eat both plants and meat?',
    options: ['Herbivores', 'Carnivores', 'Omnivores', 'Predators'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Animals',
    explanation: 'Omnivores are animals that eat both plants and meat',
    source: 'practice',
    year: 2023,
  },

  // ============================================
  // Primary 6 - Advanced Science Topics
  // ============================================
  {
    id: 'primary-sci-061',
    type: 'mcq',
    question: 'What is the largest planet in our solar system?',
    options: ['Earth', 'Mars', 'Jupiter', 'Saturn'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Solar System',
    explanation: 'Jupiter is the largest planet in our solar system',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-062',
    type: 'mcq',
    question: 'What do we call the process where plants make their own food?',
    options: ['Respiration', 'Photosynthesis', 'Digestion', 'Circulation'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Plants',
    explanation: 'Photosynthesis is the process where plants make their own food using sunlight',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-063',
    type: 'mcq',
    question: 'What do we call the smallest unit of life?',
    options: ['Tissue', 'Organ', 'Cell', 'System'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Biology',
    explanation: 'A cell is the smallest unit of life',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-064',
    type: 'mcq',
    question: 'What do we call the process where water vapor turns back to liquid?',
    options: ['Evaporation', 'Condensation', 'Precipitation', 'Transpiration'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Water Cycle',
    explanation: 'Condensation is when water vapor turns back to liquid',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-065',
    type: 'mcq',
    question: 'What do we call the force that slows down moving objects?',
    options: ['Gravity', 'Magnetism', 'Friction', 'Electricity'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Forces',
    explanation: 'Friction is the force that slows down moving objects',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-066',
    type: 'mcq',
    question: 'What do we call the system that controls our body?',
    options: ['Digestive system', 'Respiratory system', 'Nervous system', 'Circulatory system'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Human Body',
    explanation: 'The nervous system controls our body',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-067',
    type: 'mcq',
    question: 'What do we call the system that carries blood?',
    options: ['Respiratory system', 'Digestive system', 'Circulatory system', 'Nervous system'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Human Body',
    explanation: 'The circulatory system carries blood throughout the body',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-068',
    type: 'mcq',
    question: 'What is the main gas we breathe in?',
    options: ['Carbon dioxide', 'Oxygen', 'Nitrogen', 'Hydrogen'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Human Body',
    explanation: 'Oxygen is the main gas we breathe in',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-069',
    type: 'mcq',
    question: 'What is the main gas we breathe out?',
    options: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Human Body',
    explanation: 'Carbon dioxide is the main gas we breathe out',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-070',
    type: 'mcq',
    question: 'What do we call the process where animals change to survive?',
    options: ['Evolution', 'Adaptation', 'Migration', 'Hibernation'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Animals',
    explanation: 'Adaptation is when animals change to survive in their environment',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-071',
    type: 'mcq',
    question: 'How many teeth do adults usually have?',
    options: ['20', '28', '32', '36'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Body Parts',
    explanation: 'Adults usually have 32 teeth',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-072',
    type: 'mcq',
    question: 'What do we call the part of the plant that makes seeds?',
    options: ['Roots', 'Stem', 'Leaves', 'Flower'],
    correctAnswer: 3,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Plants',
    explanation: 'The flower is the part of the plant that makes seeds',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-073',
    type: 'mcq',
    question: 'Which sense helps us know if food is sweet or sour?',
    options: ['Sight', 'Hearing', 'Taste', 'Touch'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Five Senses',
    explanation: 'Taste helps us know if food is sweet or sour',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-074',
    type: 'mcq',
    question: 'What do we call the part of the body that controls everything?',
    options: ['Heart', 'Lungs', 'Brain', 'Stomach'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Body Parts',
    explanation: 'The brain controls everything in our body',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-075',
    type: 'mcq',
    question: 'Which animal is a mammal?',
    options: ['Fish', 'Bird', 'Dog', 'Snake'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Animals',
    explanation: 'A dog is a mammal (has fur and gives birth to live babies)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-076',
    type: 'mcq',
    question: 'What do we call baby plants?',
    options: ['Seeds', 'Roots', 'Seedlings', 'Leaves'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Plants',
    explanation: 'Seedlings are baby plants that have just started growing',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-077',
    type: 'mcq',
    question: 'What do we call the season with heavy rain in Ghana?',
    options: ['Dry season', 'Rainy season', 'Winter', 'Summer'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Weather',
    explanation: 'Rainy season is the season with heavy rain in Ghana',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-078',
    type: 'mcq',
    question: 'What do we call the process where ice becomes water?',
    options: ['Freezing', 'Melting', 'Evaporation', 'Condensation'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'States of Matter',
    explanation: 'Melting is when ice becomes water',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-079',
    type: 'mcq',
    question: 'What do we call the process where water becomes ice?',
    options: ['Melting', 'Freezing', 'Evaporation', 'Condensation'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'States of Matter',
    explanation: 'Freezing is when water becomes ice',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-080',
    type: 'mcq',
    question: 'Which food group helps keep our bones strong?',
    options: ['Proteins', 'Carbohydrates', 'Dairy', 'Fruits'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Food Groups',
    explanation: 'Dairy products (like milk) help keep our bones strong',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-081',
    type: 'mcq',
    question: 'What do we call the natural home of an animal?',
    options: ['House', 'Habitat', 'Cage', 'Zoo'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Habitats',
    explanation: 'Habitat is the natural home of an animal',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-082',
    type: 'mcq',
    question: 'What do we call animals that are active at night?',
    options: ['Diurnal', 'Nocturnal', 'Carnivorous', 'Herbivorous'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Animals',
    explanation: 'Nocturnal animals are active at night',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-083',
    type: 'mcq',
    question: 'What do we call the process where animals sleep through winter?',
    options: ['Migration', 'Hibernation', 'Adaptation', 'Evolution'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Animals',
    explanation: 'Hibernation is when animals sleep through winter',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-084',
    type: 'mcq',
    question: 'What do we call the process where animals move to warmer places?',
    options: ['Hibernation', 'Migration', 'Adaptation', 'Evolution'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Animals',
    explanation: 'Migration is when animals move to warmer places',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-085',
    type: 'mcq',
    question: 'What do we call the layer that protects Earth from harmful sun rays?',
    options: ['Atmosphere', 'Ozone layer', 'Clouds', 'Rain'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Environment',
    explanation: 'The ozone layer protects Earth from harmful sun rays',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-086',
    type: 'mcq',
    question: 'What do we call the process where plants take in carbon dioxide?',
    options: ['Respiration', 'Photosynthesis', 'Transpiration', 'Evaporation'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Plants',
    explanation: 'During photosynthesis, plants take in carbon dioxide',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-087',
    type: 'mcq',
    question: 'What do we call the process where plants release oxygen?',
    options: ['Respiration', 'Photosynthesis', 'Transpiration', 'Evaporation'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Plants',
    explanation: 'During photosynthesis, plants release oxygen',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-088',
    type: 'mcq',
    question: 'What do we call the natural process that breaks down waste?',
    options: ['Pollution', 'Decomposition', 'Evaporation', 'Condensation'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Environment',
    explanation: 'Decomposition is the natural process that breaks down waste',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-089',
    type: 'mcq',
    question: 'What do we call the study of weather?',
    options: ['Biology', 'Chemistry', 'Meteorology', 'Geology'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Weather',
    explanation: 'Meteorology is the study of weather',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-090',
    type: 'mcq',
    question: 'What do we call the process where scientists test ideas?',
    options: ['Observation', 'Hypothesis', 'Experiment', 'Conclusion'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Scientific Method',
    explanation: 'An experiment is when scientists test their ideas',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-091',
    type: 'mcq',
    question: 'What do we call the part of the plant that carries water?',
    options: ['Roots', 'Stem', 'Leaves', 'Flowers'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Plants',
    explanation: 'The stem carries water from roots to leaves',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-092',
    type: 'mcq',
    question: 'What do we call the part of the plant that absorbs water?',
    options: ['Stem', 'Leaves', 'Roots', 'Flowers'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Plants',
    explanation: 'Roots absorb water from the soil',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-093',
    type: 'mcq',
    question: 'What do we call the part of the plant that makes food?',
    options: ['Roots', 'Stem', 'Leaves', 'Flowers'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Plants',
    explanation: 'Leaves make food for the plant through photosynthesis',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-094',
    type: 'mcq',
    question: 'What do we call the time it takes Earth to spin once?',
    options: ['A year', 'A month', 'A day', 'An hour'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Solar System',
    explanation: 'A day is the time it takes Earth to spin once (rotation)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-095',
    type: 'mcq',
    question: 'What do we call the time it takes Earth to go around the Sun?',
    options: ['A day', 'A month', 'A year', 'A week'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Solar System',
    explanation: 'A year is the time it takes Earth to go around the Sun',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-096',
    type: 'mcq',
    question: 'What do we call the natural satellite of Earth?',
    options: ['Sun', 'Mars', 'Moon', 'Venus'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Solar System',
    explanation: 'The Moon is the natural satellite of Earth',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-097',
    type: 'mcq',
    question: 'What do we call the process where living things make more of themselves?',
    options: ['Respiration', 'Reproduction', 'Photosynthesis', 'Digestion'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Biology',
    explanation: 'Reproduction is when living things make more of themselves',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-098',
    type: 'mcq',
    question: 'What do we call the process where living things get energy from food?',
    options: ['Photosynthesis', 'Respiration', 'Digestion', 'Circulation'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Biology',
    explanation: 'Respiration is when living things get energy from food',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-099',
    type: 'mcq',
    question: 'What do we call the process where waste is removed from the body?',
    options: ['Digestion', 'Respiration', 'Excretion', 'Circulation'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Human Body',
    explanation: 'Excretion is when waste is removed from the body',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-sci-100',
    type: 'mcq',
    question: 'What do we call the ability of living things to respond to changes?',
    options: ['Respiration', 'Reproduction', 'Sensitivity', 'Growth'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Biology',
    explanation: 'Sensitivity is the ability of living things to respond to changes',
    source: 'practice',
    year: 2023,
  },
];

