// Primary Social Studies Questions
// Initial batch of questions migrated to modular ChallengeQuestion format

import type { ChallengeQuestion } from '../types';

export const primarySocialStudiesQuestions: ChallengeQuestion[] = [
  // ============================================
  // MCQ Questions (Initial Batch)
  // ============================================

  // Primary Social Studies - Geography
  {
    id: 'primary-soc-001',
    type: 'mcq',
    question: 'What is the name of your country?',
    options: ['Ghana', 'Nigeria', 'Sierra Leone', 'All of the above'],
    correctAnswer: 3,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Geography',
    explanation: 'All are countries in West Africa',
    source: 'practice',
  },
  {
    id: 'primary-soc-002',
    type: 'mcq',
    question: 'The capital city of Ghana is...',
    options: ['Kumasi', 'Accra', 'Tamale', 'Cape Coast'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Geography',
    explanation: 'Accra is the capital city of Ghana',
    source: 'practice',
  },

  // Primary Social Studies - Citizenship
  {
    id: 'primary-soc-003',
    type: 'mcq',
    question: 'What do we call the leader of a country?',
    options: ['Teacher', 'President', 'Doctor', 'Farmer'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Citizenship',
    explanation: 'The leader of a country is called the President',
    source: 'practice',
  },
  {
    id: 'primary-soc-004',
    type: 'mcq',
    question: 'Who is the head of a family?',
    options: ['Mother', 'Father', 'Uncle', 'Aunt'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Citizenship',
    explanation: 'Traditionally, the father is the head of the family',
    source: 'practice',
  },
  {
    id: 'primary-soc-005',
    type: 'mcq',
    question: 'We should respect our...',
    options: ['Friends only', 'Teachers and parents', 'Nobody', 'Only ourselves'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Citizenship',
    explanation: 'We should respect our teachers and parents',
    source: 'practice',
  },

  // Primary Social Studies - Culture
  {
    id: 'primary-soc-006',
    type: 'mcq',
    question: 'Which of these is a traditional food?',
    options: ['Pizza', 'Banku', 'Burger', 'Hot dog'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Culture',
    explanation: 'Banku is a traditional Ghanaian food',
    source: 'practice',
  },
  {
    id: 'primary-soc-007',
    type: 'mcq',
    question: 'We celebrate Independence Day on...',
    options: ['January 1st', 'March 6th', 'December 25th', 'June 1st'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'History',
    explanation: 'Ghana celebrates Independence Day on March 6th',
    source: 'practice',
  },
  {
    id: 'primary-soc-008',
    type: 'mcq',
    question: 'Which of these is a national symbol?',
    options: ['Flag', 'Car', 'House', 'School'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Citizenship',
    explanation: 'The flag is a national symbol',
    source: 'practice',
  },
  {
    id: 'primary-soc-009',
    type: 'mcq',
    question: 'We should keep our environment...',
    options: ['Dirty', 'Clean', 'Messy', 'Untidy'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Environment',
    explanation: 'We should keep our environment clean',
    source: 'practice',
  },
  {
    id: 'primary-soc-010',
    type: 'mcq',
    question: 'Which of these helps us learn?',
    options: ['School', 'Playground', 'Market', 'Park'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Education',
    explanation: 'School is where we go to learn',
    source: 'practice',
  },

  // ============================================
  // Primary 1 - Family, School & Community
  // ============================================
  {
    id: 'primary-soc-011',
    type: 'mcq',
    question: 'Who are the members of a family?',
    options: ['Only parents', 'Parents and children', 'Only children', 'Only friends'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Family',
    explanation: 'A family includes parents and children',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-012',
    type: 'mcq',
    question: 'What do we call our father\'s father?',
    options: ['Uncle', 'Grandfather', 'Cousin', 'Brother'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Family',
    explanation: 'Our father\'s father is our grandfather',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-013',
    type: 'mcq',
    question: 'What do we call our mother\'s mother?',
    options: ['Aunt', 'Grandmother', 'Cousin', 'Sister'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Family',
    explanation: 'Our mother\'s mother is our grandmother',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-014',
    type: 'mcq',
    question: 'Where do we go to learn?',
    options: ['Market', 'Hospital', 'School', 'Park'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Education',
    explanation: 'We go to school to learn',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-015',
    type: 'mcq',
    question: 'Who teaches us in school?',
    options: ['Doctors', 'Teachers', 'Farmers', 'Drivers'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Education',
    explanation: 'Teachers teach us in school',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-016',
    type: 'mcq',
    question: 'What do we call the people who live near us?',
    options: ['Family', 'Neighbors', 'Teachers', 'Doctors'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Community',
    explanation: 'Neighbors are people who live near us',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-017',
    type: 'mcq',
    question: 'What should we do to keep our community clean?',
    options: ['Throw trash anywhere', 'Put trash in bins', 'Burn all trash', 'Leave trash on the ground'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Environment',
    explanation: 'We should put trash in bins to keep our community clean',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-018',
    type: 'mcq',
    question: 'What do we call the place where we buy food?',
    options: ['School', 'Hospital', 'Market', 'Park'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Community',
    explanation: 'We buy food at the market',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-019',
    type: 'mcq',
    question: 'What do we call the place where sick people go?',
    options: ['School', 'Hospital', 'Market', 'Park'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Community',
    explanation: 'Sick people go to the hospital',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-020',
    type: 'mcq',
    question: 'What should we say when someone helps us?',
    options: ['Thank you', 'Goodbye', 'Hello', 'Sorry'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Citizenship',
    explanation: 'We should say "Thank you" when someone helps us',
    source: 'practice',
    year: 2023,
  },

  // ============================================
  // Primary 2 - Ghana Geography & Culture
  // ============================================
  {
    id: 'primary-soc-021',
    type: 'mcq',
    question: 'How many regions are in Ghana?',
    options: ['10', '14', '16', '18'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Geography',
    explanation: 'Ghana has 16 regions',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-022',
    type: 'mcq',
    question: 'Which region is the capital city in?',
    options: ['Ashanti Region', 'Greater Accra Region', 'Northern Region', 'Western Region'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Geography',
    explanation: 'Accra, the capital, is in the Greater Accra Region',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-023',
    type: 'mcq',
    question: 'What is the largest region in Ghana?',
    options: ['Greater Accra', 'Ashanti', 'Northern', 'Western'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Geography',
    explanation: 'The Northern Region is the largest region in Ghana',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-024',
    type: 'mcq',
    question: 'Which traditional food is made from cassava?',
    options: ['Jollof rice', 'Fufu', 'Banku', 'Both B and C'],
    correctAnswer: 3,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Culture',
    explanation: 'Both fufu and banku can be made from cassava',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-025',
    type: 'mcq',
    question: 'What do we call the traditional cloth of Ghana?',
    options: ['Kente', 'Cotton', 'Silk', 'Linen'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Culture',
    explanation: 'Kente is the traditional cloth of Ghana',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-026',
    type: 'mcq',
    question: 'What do we call the traditional drum of Ghana?',
    options: ['Piano', 'Guitar', 'Fontomfrom', 'Violin'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Culture',
    explanation: 'Fontomfrom is a traditional drum of Ghana',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-027',
    type: 'mcq',
    question: 'What should we do when we meet an elder?',
    options: ['Ignore them', 'Greet them respectfully', 'Run away', 'Shout at them'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Citizenship',
    explanation: 'We should greet elders respectfully',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-028',
    type: 'mcq',
    question: 'What do we call the traditional leader of a community?',
    options: ['President', 'Chief', 'Teacher', 'Doctor'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Citizenship',
    explanation: 'The traditional leader of a community is called a Chief',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-029',
    type: 'mcq',
    question: 'What do we call the traditional festival in Ghana?',
    options: ['Christmas', 'Easter', 'Hogbetsotso', 'New Year'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Culture',
    explanation: 'Hogbetsotso is a traditional festival in Ghana',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-030',
    type: 'mcq',
    question: 'What is the main language spoken in Ghana?',
    options: ['French', 'English', 'Spanish', 'Portuguese'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Culture',
    explanation: 'English is the main language spoken in Ghana',
    source: 'practice',
    year: 2023,
  },

  // ============================================
  // Primary 3 - History & National Symbols
  // ============================================
  {
    id: 'primary-soc-031',
    type: 'mcq',
    question: 'Who was the first President of Ghana?',
    options: ['Kwame Nkrumah', 'Jerry Rawlings', 'John Kufuor', 'Nana Akufo-Addo'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'History',
    explanation: 'Kwame Nkrumah was the first President of Ghana',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-032',
    type: 'mcq',
    question: 'In what year did Ghana gain independence?',
    options: ['1955', '1957', '1960', '1965'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'History',
    explanation: 'Ghana gained independence in 1957',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-033',
    type: 'mcq',
    question: 'What are the colors of the Ghana flag?',
    options: ['Red, white, blue', 'Red, yellow, green, black star', 'Blue, white, red', 'Green, yellow, red'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'National Symbols',
    explanation: 'The Ghana flag has red, yellow, green, and a black star',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-034',
    type: 'mcq',
    question: 'What is the national animal of Ghana?',
    options: ['Lion', 'Elephant', 'Eagle', 'Leopard'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'National Symbols',
    explanation: 'The elephant is the national animal of Ghana',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-035',
    type: 'mcq',
    question: 'What is the motto of Ghana?',
    options: ['Unity and Strength', 'Freedom and Justice', 'Peace and Progress', 'Hope and Faith'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'National Symbols',
    explanation: 'The motto of Ghana is "Freedom and Justice"',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-036',
    type: 'mcq',
    question: 'What do we call the person who makes laws?',
    options: ['President', 'Chief', 'Parliamentarian', 'Teacher'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Government',
    explanation: 'A Parliamentarian makes laws in Parliament',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-037',
    type: 'mcq',
    question: 'What do we call the place where laws are made?',
    options: ['School', 'Hospital', 'Parliament', 'Market'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Government',
    explanation: 'Parliament is where laws are made',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-038',
    type: 'mcq',
    question: 'What do we call the money used in Ghana?',
    options: ['Dollar', 'Pound', 'Cedi', 'Euro'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Economy',
    explanation: 'The money used in Ghana is called Cedi',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-039',
    type: 'mcq',
    question: 'What do we call the person who enforces laws?',
    options: ['Teacher', 'Doctor', 'Police officer', 'Farmer'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Government',
    explanation: 'Police officers enforce laws',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-040',
    type: 'mcq',
    question: 'What should we do to show respect to our country?',
    options: ['Ignore the flag', 'Stand when the national anthem plays', 'Disrespect leaders', 'Break laws'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Citizenship',
    explanation: 'We should stand when the national anthem plays to show respect',
    source: 'practice',
    year: 2023,
  },

  // ============================================
  // Primary 4 - Government & Economy
  // ============================================
  {
    id: 'primary-soc-041',
    type: 'mcq',
    question: 'What do we call the system of government in Ghana?',
    options: ['Monarchy', 'Democracy', 'Dictatorship', 'Anarchy'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Government',
    explanation: 'Ghana has a democratic system of government',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-042',
    type: 'mcq',
    question: 'How often do we vote for a new President?',
    options: ['Every 2 years', 'Every 4 years', 'Every 6 years', 'Every 8 years'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Government',
    explanation: 'We vote for a new President every 4 years',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-043',
    type: 'mcq',
    question: 'What do we call the exchange of goods for money?',
    options: ['Gift', 'Trade', 'Donation', 'Loan'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Economy',
    explanation: 'Trade is the exchange of goods for money',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-044',
    type: 'mcq',
    question: 'What is the main export of Ghana?',
    options: ['Rice', 'Gold', 'Water', 'Sand'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Economy',
    explanation: 'Gold is one of the main exports of Ghana',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-045',
    type: 'mcq',
    question: 'What do we call the natural resources found in Ghana?',
    options: ['Imports', 'Exports', 'Minerals', 'Manufactured goods'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Resources',
    explanation: 'Minerals are natural resources found in Ghana (gold, diamond, etc.)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-046',
    type: 'mcq',
    question: 'What should we do to protect our natural resources?',
    options: ['Use them all quickly', 'Waste them', 'Use them wisely', 'Ignore them'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Environment',
    explanation: 'We should use natural resources wisely to protect them',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-047',
    type: 'mcq',
    question: 'What do we call the process of choosing leaders?',
    options: ['Appointment', 'Election', 'Selection', 'Nomination'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Government',
    explanation: 'Election is the process of choosing leaders by voting',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-048',
    type: 'mcq',
    question: 'What do we call the rights we have as citizens?',
    options: ['Duties', 'Responsibilities', 'Rights', 'Obligations'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Citizenship',
    explanation: 'Rights are what we are entitled to as citizens',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-049',
    type: 'mcq',
    question: 'What do we call the things we must do as citizens?',
    options: ['Rights', 'Responsibilities', 'Privileges', 'Benefits'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Citizenship',
    explanation: 'Responsibilities are things we must do as citizens',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-050',
    type: 'mcq',
    question: 'What do we call the study of the Earth and its features?',
    options: ['History', 'Geography', 'Science', 'Mathematics'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Geography',
    explanation: 'Geography is the study of the Earth and its features',
    source: 'practice',
    year: 2023,
  },

  // ============================================
  // Primary 5 - West Africa & Development
  // ============================================
  {
    id: 'primary-soc-051',
    type: 'mcq',
    question: 'Which country is to the east of Ghana?',
    options: ['Togo', 'Burkina Faso', 'Côte d\'Ivoire', 'Nigeria'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Geography',
    explanation: 'Togo is to the east of Ghana',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-052',
    type: 'mcq',
    question: 'Which country is to the west of Ghana?',
    options: ['Togo', 'Burkina Faso', 'Côte d\'Ivoire', 'Nigeria'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Geography',
    explanation: 'Côte d\'Ivoire is to the west of Ghana',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-053',
    type: 'mcq',
    question: 'Which country is to the north of Ghana?',
    options: ['Togo', 'Burkina Faso', 'Côte d\'Ivoire', 'Nigeria'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Geography',
    explanation: 'Burkina Faso is to the north of Ghana',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-054',
    type: 'mcq',
    question: 'What is the main body of water to the south of Ghana?',
    options: ['Lake Volta', 'Atlantic Ocean', 'Gulf of Guinea', 'Both B and C'],
    correctAnswer: 3,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Geography',
    explanation: 'The Atlantic Ocean and Gulf of Guinea are to the south of Ghana',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-055',
    type: 'mcq',
    question: 'What do we call the exchange of goods between countries?',
    options: ['Local trade', 'International trade', 'Domestic trade', 'Internal trade'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Economy',
    explanation: 'International trade is the exchange of goods between countries',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-056',
    type: 'mcq',
    question: 'What do we call the process of making a country better?',
    options: ['Destruction', 'Development', 'Decline', 'Decay'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Development',
    explanation: 'Development is the process of making a country better',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-057',
    type: 'mcq',
    question: 'What do we call the organization of African countries?',
    options: ['United Nations', 'African Union', 'European Union', 'ASEAN'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'International Relations',
    explanation: 'The African Union is the organization of African countries',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-058',
    type: 'mcq',
    question: 'What do we call the problem of not having enough food?',
    options: ['Obesity', 'Hunger', 'Thirst', 'Tiredness'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Social Issues',
    explanation: 'Hunger is the problem of not having enough food',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-059',
    type: 'mcq',
    question: 'What do we call the problem of not having clean water?',
    options: ['Thirst', 'Water shortage', 'Drought', 'All of the above'],
    correctAnswer: 3,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Social Issues',
    explanation: 'Water shortage, drought, and thirst are all related to not having clean water',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-060',
    type: 'mcq',
    question: 'What do we call the process of learning new skills?',
    options: ['Education', 'Training', 'Both A and B', 'None of the above'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Education',
    explanation: 'Both education and training help us learn new skills',
    source: 'practice',
    year: 2023,
  },

  // ============================================
  // Primary 6 - Advanced Geography & History
  // ============================================
  {
    id: 'primary-soc-061',
    type: 'mcq',
    question: 'What is the largest lake in Ghana?',
    options: ['Lake Bosomtwe', 'Lake Volta', 'Lake Keta', 'Lake Tano'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Geography',
    explanation: 'Lake Volta is the largest lake in Ghana',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-062',
    type: 'mcq',
    question: 'What is the highest mountain in Ghana?',
    options: ['Mount Afadja', 'Mount Aduadu', 'Mount Atiwa', 'Mount Aburi'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Geography',
    explanation: 'Mount Afadja (also called Mount Afadjato) is the highest mountain in Ghana',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-063',
    type: 'mcq',
    question: 'What do we call the period before Ghana gained independence?',
    options: ['Post-colonial', 'Colonial period', 'Modern period', 'Ancient period'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'History',
    explanation: 'The colonial period was before Ghana gained independence',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-064',
    type: 'mcq',
    question: 'Which European country colonized Ghana?',
    options: ['France', 'Portugal', 'Britain', 'Germany'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'History',
    explanation: 'Britain (United Kingdom) colonized Ghana',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-065',
    type: 'mcq',
    question: 'What do we call the movement that led to Ghana\'s independence?',
    options: ['Colonial movement', 'Independence movement', 'Revolutionary movement', 'Peaceful movement'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'History',
    explanation: 'The independence movement led to Ghana\'s independence',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-066',
    type: 'mcq',
    question: 'What do we call the system where people own property?',
    options: ['Communism', 'Socialism', 'Capitalism', 'Feudalism'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Economy',
    explanation: 'Capitalism is the system where people own property',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-067',
    type: 'mcq',
    question: 'What do we call the organization that helps countries work together?',
    options: ['African Union', 'United Nations', 'European Union', 'All of the above'],
    correctAnswer: 3,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'International Relations',
    explanation: 'All these organizations help countries work together',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-068',
    type: 'mcq',
    question: 'What do we call the problem of too many people in one area?',
    options: ['Underpopulation', 'Overpopulation', 'Migration', 'Urbanization'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Social Issues',
    explanation: 'Overpopulation is when there are too many people in one area',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-069',
    type: 'mcq',
    question: 'What do we call the movement of people from rural to urban areas?',
    options: ['Migration', 'Urbanization', 'Emigration', 'Immigration'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Social Issues',
    explanation: 'Urbanization is the movement of people from rural to urban areas',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-070',
    type: 'mcq',
    question: 'What do we call the protection of natural resources for future generations?',
    options: ['Exploitation', 'Conservation', 'Destruction', 'Waste'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Environment',
    explanation: 'Conservation is the protection of natural resources for future generations',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-071',
    type: 'mcq',
    question: 'What is the second largest city in Ghana?',
    options: ['Accra', 'Kumasi', 'Tamale', 'Cape Coast'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Geography',
    explanation: 'Kumasi is the second largest city in Ghana',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-072',
    type: 'mcq',
    question: 'What do we call the traditional ruler of the Ashanti people?',
    options: ['Chief', 'King', 'Asantehene', 'Omanhene'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Culture',
    explanation: 'The Asantehene is the traditional ruler of the Ashanti people',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-073',
    type: 'mcq',
    question: 'What do we call the traditional stool of the Ashanti?',
    options: ['Golden Stool', 'Silver Stool', 'Wooden Stool', 'Iron Stool'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Culture',
    explanation: 'The Golden Stool is the traditional stool of the Ashanti',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-074',
    type: 'mcq',
    question: 'What do we call the traditional food made from plantain and cassava?',
    options: ['Fufu', 'Banku', 'Kokonte', 'Ampesi'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Culture',
    explanation: 'Banku is made from plantain and cassava',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-075',
    type: 'mcq',
    question: 'What do we call the traditional food made from yam, plantain, or cassava?',
    options: ['Banku', 'Fufu', 'Jollof rice', 'Waakye'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Culture',
    explanation: 'Fufu is made from yam, plantain, or cassava',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-076',
    type: 'mcq',
    question: 'What do we call the traditional dance of Ghana?',
    options: ['Hip-hop', 'Ballet', 'Adowa', 'Salsa'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Culture',
    explanation: 'Adowa is a traditional dance of Ghana',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-077',
    type: 'mcq',
    question: 'What do we call the traditional music instrument made from gourds?',
    options: ['Piano', 'Guitar', 'Shekere', 'Violin'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Culture',
    explanation: 'Shekere is a traditional music instrument made from gourds',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-078',
    type: 'mcq',
    question: 'What do we call the traditional festival of the Ga people?',
    options: ['Hogbetsotso', 'Homowo', 'Aboakyir', 'Bakatue'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Culture',
    explanation: 'Homowo is the traditional festival of the Ga people',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-079',
    type: 'mcq',
    question: 'What do we call the traditional festival of the Ewe people?',
    options: ['Homowo', 'Hogbetsotso', 'Aboakyir', 'Bakatue'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Culture',
    explanation: 'Hogbetsotso is the traditional festival of the Ewe people',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-080',
    type: 'mcq',
    question: 'What do we call the problem of unfair treatment?',
    options: ['Justice', 'Equality', 'Discrimination', 'Fairness'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Social Issues',
    explanation: 'Discrimination is the problem of unfair treatment',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-081',
    type: 'mcq',
    question: 'What do we call the problem of not having a home?',
    options: ['Poverty', 'Homelessness', 'Hunger', 'Illness'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Social Issues',
    explanation: 'Homelessness is the problem of not having a home',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-082',
    type: 'mcq',
    question: 'What do we call the problem of not having enough money?',
    options: ['Wealth', 'Poverty', 'Richness', 'Prosperity'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Social Issues',
    explanation: 'Poverty is the problem of not having enough money',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-083',
    type: 'mcq',
    question: 'What do we call the process of making goods in factories?',
    options: ['Agriculture', 'Manufacturing', 'Mining', 'Fishing'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Economy',
    explanation: 'Manufacturing is the process of making goods in factories',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-084',
    type: 'mcq',
    question: 'What do we call the process of growing crops?',
    options: ['Manufacturing', 'Agriculture', 'Mining', 'Fishing'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Economy',
    explanation: 'Agriculture is the process of growing crops',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-085',
    type: 'mcq',
    question: 'What do we call the process of getting minerals from the ground?',
    options: ['Agriculture', 'Manufacturing', 'Mining', 'Fishing'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Economy',
    explanation: 'Mining is the process of getting minerals from the ground',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-086',
    type: 'mcq',
    question: 'What do we call the main crop grown in Ghana?',
    options: ['Wheat', 'Rice', 'Cocoa', 'Coffee'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Economy',
    explanation: 'Cocoa is one of the main crops grown in Ghana',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-087',
    type: 'mcq',
    question: 'What do we call the problem of cutting down too many trees?',
    options: ['Reforestation', 'Deforestation', 'Afforestation', 'Conservation'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Environment',
    explanation: 'Deforestation is the problem of cutting down too many trees',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-088',
    type: 'mcq',
    question: 'What do we call the planting of new trees?',
    options: ['Deforestation', 'Reforestation', 'Desertification', 'Pollution'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Environment',
    explanation: 'Reforestation is the planting of new trees',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-089',
    type: 'mcq',
    question: 'What do we call the problem of dirty air, water, or land?',
    options: ['Conservation', 'Pollution', 'Protection', 'Preservation'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Environment',
    explanation: 'Pollution is the problem of dirty air, water, or land',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-090',
    type: 'mcq',
    question: 'What do we call the study of past events?',
    options: ['Geography', 'History', 'Science', 'Mathematics'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'History',
    explanation: 'History is the study of past events',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-091',
    type: 'mcq',
    question: 'What do we call the person who studies history?',
    options: ['Geographer', 'Historian', 'Scientist', 'Mathematician'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'History',
    explanation: 'A historian is a person who studies history',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-092',
    type: 'mcq',
    question: 'What do we call the person who studies geography?',
    options: ['Historian', 'Geographer', 'Scientist', 'Mathematician'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Geography',
    explanation: 'A geographer is a person who studies geography',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-093',
    type: 'mcq',
    question: 'What do we call the line that divides the Earth into north and south?',
    options: ['Equator', 'Prime Meridian', 'Tropic of Cancer', 'Tropic of Capricorn'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Geography',
    explanation: 'The Equator divides the Earth into north and south',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-094',
    type: 'mcq',
    question: 'What continent is Ghana in?',
    options: ['Asia', 'Europe', 'Africa', 'America'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Geography',
    explanation: 'Ghana is in Africa',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-095',
    type: 'mcq',
    question: 'What do we call the group of countries in West Africa?',
    options: ['ECOWAS', 'AU', 'UN', 'EU'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'International Relations',
    explanation: 'ECOWAS (Economic Community of West African States) is the group of countries in West Africa',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-096',
    type: 'mcq',
    question: 'What do we call the system where people vote for leaders?',
    options: ['Dictatorship', 'Democracy', 'Monarchy', 'Anarchy'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Government',
    explanation: 'Democracy is the system where people vote for leaders',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-097',
    type: 'mcq',
    question: 'What do we call the document that contains the laws of a country?',
    options: ['Book', 'Constitution', 'Magazine', 'Newspaper'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Government',
    explanation: 'The Constitution contains the laws of a country',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-098',
    type: 'mcq',
    question: 'What do we call the process of making something new?',
    options: ['Destruction', 'Innovation', 'Tradition', 'Conservation'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Development',
    explanation: 'Innovation is the process of making something new',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-099',
    type: 'mcq',
    question: 'What do we call the ability to read and write?',
    options: ['Illiteracy', 'Literacy', 'Education', 'Training'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Education',
    explanation: 'Literacy is the ability to read and write',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-soc-100',
    type: 'mcq',
    question: 'What do we call the problem of not being able to read and write?',
    options: ['Literacy', 'Illiteracy', 'Education', 'Training'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Education',
    explanation: 'Illiteracy is the problem of not being able to read and write',
    source: 'practice',
    year: 2023,
  },
];

