import type { ChallengeQuestion } from '../types';

/**
 * JHS Creative Arts Question Bank
 * BECE Creative Arts / Cultural and Creative Arts
 * Topics: Visual Arts, Music, Drama, Dance, Crafts
 */

export const jhsCreativeArtsQuestions: ChallengeQuestion[] = [
  // ============================================
  // Visual Arts - Color Theory & Basics
  // ============================================
  {
    id: 'jhs-ca-001',
    type: 'mcq',
    question: 'Which of these is a primary color?',
    options: ['Green', 'Orange', 'Red', 'Purple'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Red, blue, and yellow are primary colors that cannot be made by mixing other colors.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-002',
    type: 'mcq',
    question: 'Which color is made by mixing red and yellow?',
    options: ['Green', 'Orange', 'Blue', 'Purple'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Red + Yellow = Orange.',
    source: 'practice',
    year: 2016,
  },
  {
    id: 'jhs-ca-003',
    type: 'mcq',
    question: 'Which of these is a secondary color?',
    options: ['Red', 'Blue', 'Green', 'Yellow'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Green is made by mixing blue and yellow (two primary colors).',
    source: 'practice',
    year: 2018,
  },
  {
    id: 'jhs-ca-004',
    type: 'mcq',
    question: 'Which of these is a warm color?',
    options: ['Blue', 'Green', 'Red', 'Purple'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Red, orange, and yellow are warm colors that evoke warmth and energy.',
    source: 'practice',
    year: 2016,
  },
  {
    id: 'jhs-ca-005',
    type: 'mcq',
    question: 'Which of these is a cool color?',
    options: ['Red', 'Orange', 'Blue', 'Yellow'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Blue, green, and purple are cool colors that evoke calmness and tranquility.',
    source: 'practice',
    year: 2018,
  },
  {
    id: 'jhs-ca-006',
    type: 'mcq',
    question: 'What color is made by mixing red and blue?',
    options: ['Green', 'Orange', 'Purple', 'Yellow'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Red + Blue = Purple (or violet).',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-007',
    type: 'mcq',
    question: 'What color is made by mixing blue and yellow?',
    options: ['Green', 'Orange', 'Purple', 'Red'],
    correctAnswer: 0,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Blue + Yellow = Green.',
    source: 'practice',
    year: 2020,
  },

  // ============================================
  // Visual Arts - Drawing & Painting
  // ============================================
  {
    id: 'jhs-ca-008',
    type: 'mcq',
    question: 'A drawing made with pencil is called a...',
    options: ['Painting', 'Sketch', 'Sculpture', 'Collage'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Sketches are quick pencil drawings used to plan or practice.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ca-009',
    type: 'mcq',
    question: 'The art of cutting and pasting paper is called...',
    options: ['Drawing', 'Collage', 'Painting', 'Sculpting'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Collage involves arranging cut paper pieces to create artwork.',
    source: 'practice',
    year: 2015,
  },
  {
    id: 'jhs-ca-010',
    type: 'mcq',
    question: 'Which tool is used for painting?',
    options: ['Pencil', 'Brush', 'Chisel', 'Needle'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Brushes are used to apply paint to canvas or paper.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-011',
    type: 'mcq',
    question: 'What is the surface used for painting called?',
    options: ['Paper', 'Canvas', 'Wood', 'All of the above'],
    correctAnswer: 3,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Paintings can be done on various surfaces including paper, canvas, and wood.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-012',
    type: 'mcq',
    question: 'Which of these is a drawing tool?',
    options: ['Brush', 'Chisel', 'Pencil', 'Hammer'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Pencils are primary drawing tools for creating sketches and drawings.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ca-013',
    type: 'mcq',
    question: 'What is the art of creating images using lines and shading called?',
    options: ['Painting', 'Drawing', 'Sculpture', 'Printing'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Drawing uses lines, shapes, and shading to create images.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-014',
    type: 'mcq',
    question: 'Which type of paint dries quickly?',
    options: ['Oil paint', 'Watercolor', 'Acrylic paint', 'All dry at same speed'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Acrylic paint dries faster than oil paint and is water-soluble.',
    source: 'practice',
    year: 2020,
  },

  // ============================================
  // Visual Arts - Sculpture & 3D Art
  // ============================================
  {
    id: 'jhs-ca-015',
    type: 'mcq',
    question: 'The art of creating three-dimensional objects is called...',
    options: ['Drawing', 'Painting', 'Sculpture', 'Printing'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Sculpture creates 3D art forms that can be viewed from all sides.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-016',
    type: 'mcq',
    question: 'The art of making pots from clay is called...',
    options: ['Sculpting', 'Pottery', 'Weaving', 'Carving'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Crafts',
    explanation: 'Pottery involves shaping clay into vessels and firing them in a kiln.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-017',
    type: 'mcq',
    question: 'What material is commonly used for making sculptures?',
    options: ['Paper', 'Water', 'Clay', 'Paint'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Clay is a common material for sculpting as it is malleable and can be fired.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-018',
    type: 'mcq',
    question: 'The art of cutting designs into wood or stone is called...',
    options: ['Painting', 'Drawing', 'Carving', 'Weaving'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Crafts',
    explanation: 'Carving involves removing material to create designs or shapes.',
    source: 'practice',
    year: 2019,
  },

  // ============================================
  // Music - Instruments
  // ============================================
  {
    id: 'jhs-ca-019',
    type: 'mcq',
    question: 'Which instrument is played by striking?',
    options: ['Flute', 'Drum', 'Guitar', 'Piano'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Music',
    explanation: 'Drums are percussion instruments played by striking with hands or sticks.',
    source: 'practice',
    year: 2018,
  },
  {
    id: 'jhs-ca-020',
    type: 'mcq',
    question: 'Which of these is a string instrument?',
    options: ['Drum', 'Flute', 'Guitar', 'Trumpet'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Music',
    explanation: 'Guitar has strings that are plucked or strummed to produce sound.',
    source: 'practice',
    year: 2017,
  },
  {
    id: 'jhs-ca-021',
    type: 'mcq',
    question: 'Which of these is a wind instrument?',
    options: ['Piano', 'Violin', 'Flute', 'Drum'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Music',
    explanation: 'Flute produces sound when air is blown through it.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-022',
    type: 'mcq',
    question: 'Which instrument is part of the brass family?',
    options: ['Violin', 'Flute', 'Trumpet', 'Piano'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Music',
    explanation: 'Trumpet is a brass instrument that produces sound by vibrating lips.',
    source: 'practice',
    year: 2015,
  },
  {
    id: 'jhs-ca-023',
    type: 'mcq',
    question: 'Which of these is a percussion instrument?',
    options: ['Violin', 'Flute', 'Piano', 'Trumpet'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Music',
    explanation: 'Piano produces sound when keys are struck, making it a percussion instrument.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-024',
    type: 'mcq',
    question: 'A traditional Ghanaian drum is called...',
    options: ['Piano', 'Guitar', 'Fontomfrom', 'Violin'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Music',
    explanation: 'Fontomfrom is a traditional Akan drum used in Ghanaian ceremonies.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-025',
    type: 'mcq',
    question: 'Which instrument has keys?',
    options: ['Guitar', 'Drum', 'Piano', 'Flute'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Music',
    explanation: 'Piano has keys that are pressed to produce musical notes.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ca-026',
    type: 'mcq',
    question: 'Which of these is a woodwind instrument?',
    options: ['Trumpet', 'Violin', 'Clarinet', 'Drum'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Music',
    explanation: 'Clarinet is a woodwind instrument that uses a reed to produce sound.',
    source: 'practice',
    year: 2021,
  },

  // ============================================
  // Music - Theory & Concepts
  // ============================================
  {
    id: 'jhs-ca-027',
    type: 'mcq',
    question: 'Which musical note has the longest duration?',
    options: ['Whole note', 'Half note', 'Quarter note', 'Eighth note'],
    correctAnswer: 0,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Music',
    explanation: 'Whole notes last for 4 beats, the longest standard note duration.',
    source: 'practice',
    year: 2017,
  },
  {
    id: 'jhs-ca-028',
    type: 'mcq',
    question: 'A group of musicians playing together is called an...',
    options: ['Solo', 'Duet', 'Orchestra', 'Quartet'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Music',
    explanation: 'Orchestras have many musicians playing different instruments together.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-029',
    type: 'mcq',
    question: 'What is the speed of music called?',
    options: ['Pitch', 'Tempo', 'Volume', 'Rhythm'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Music',
    explanation: 'Tempo refers to the speed or pace of a musical piece.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-030',
    type: 'mcq',
    question: 'What is the highness or lowness of a sound called?',
    options: ['Tempo', 'Pitch', 'Volume', 'Rhythm'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Music',
    explanation: 'Pitch refers to how high or low a musical note sounds.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ca-031',
    type: 'mcq',
    question: 'How many lines are in a musical staff?',
    options: ['Three', 'Four', 'Five', 'Six'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Music',
    explanation: 'A standard musical staff has five horizontal lines for writing notes.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-032',
    type: 'mcq',
    question: 'What is a group of two musicians called?',
    options: ['Solo', 'Duet', 'Trio', 'Quartet'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Music',
    explanation: 'A duet is a musical performance by two people.',
    source: 'practice',
    year: 2020,
  },

  // ============================================
  // Drama & Theatre
  // ============================================
  {
    id: 'jhs-ca-033',
    type: 'mcq',
    question: 'A play performed on stage is called a...',
    options: ['Movie', 'Drama', 'Song', 'Poem'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Drama',
    explanation: 'Drama is live theatrical performance on stage.',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-ca-034',
    type: 'mcq',
    question: 'A person who acts in a play is called an...',
    options: ['Director', 'Actor', 'Producer', 'Writer'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Drama',
    explanation: 'Actors perform roles in dramas and plays.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ca-035',
    type: 'mcq',
    question: 'The person who writes a play is called a...',
    options: ['Actor', 'Director', 'Playwright', 'Producer'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Drama',
    explanation: 'Playwrights create scripts for plays.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ca-036',
    type: 'mcq',
    question: 'The person who guides actors in a play is called a...',
    options: ['Actor', 'Playwright', 'Director', 'Producer'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Drama',
    explanation: 'Directors guide actors and oversee the overall production of a play.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-037',
    type: 'mcq',
    question: 'What is the written text of a play called?',
    options: ['Script', 'Novel', 'Poem', 'Song'],
    correctAnswer: 0,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Drama',
    explanation: 'A script contains the dialogue and stage directions for a play.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-038',
    type: 'mcq',
    question: 'What is the area where actors perform called?',
    options: ['Backstage', 'Stage', 'Audience', 'Lobby'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Drama',
    explanation: 'The stage is the raised platform where actors perform.',
    source: 'practice',
    year: 2020,
  },

  // ============================================
  // Dance
  // ============================================
  {
    id: 'jhs-ca-039',
    type: 'mcq',
    question: 'A traditional Ghanaian dance is...',
    options: ['Ballet', 'Adowa', 'Hip-hop', 'Jazz'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Dance',
    explanation: 'Adowa is a popular traditional dance in Ghana, especially among the Akan people.',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-ca-040',
    type: 'mcq',
    question: 'What is a group of dancers called?',
    options: ['Choir', 'Band', 'Troupe', 'Orchestra'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Dance',
    explanation: 'A troupe is a group of dancers who perform together.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-041',
    type: 'mcq',
    question: 'Which traditional Ghanaian dance is performed at funerals?',
    options: ['Adowa', 'Kpanlogo', 'Bamaya', 'All of the above'],
    correctAnswer: 3,
    subject: 'Creative Arts',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Dance',
    explanation: 'Many traditional Ghanaian dances, including Adowa, Kpanlogo, and Bamaya, are performed at funerals.',
    source: 'practice',
    year: 2020,
  },

  // ============================================
  // Crafts
  // ============================================
  {
    id: 'jhs-ca-042',
    type: 'mcq',
    question: 'The art of making designs with thread is called...',
    options: ['Weaving', 'Pottery', 'Carving', 'Painting'],
    correctAnswer: 0,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Crafts',
    explanation: 'Weaving creates patterns with threads on a loom.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-043',
    type: 'mcq',
    question: 'What is the art of making baskets called?',
    options: ['Pottery', 'Weaving', 'Carving', 'Painting'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Crafts',
    explanation: 'Basket weaving involves interlacing materials like grass or reeds.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-044',
    type: 'mcq',
    question: 'What material is commonly used for making kente cloth?',
    options: ['Cotton', 'Silk', 'Wool', 'All of the above'],
    correctAnswer: 3,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Crafts',
    explanation: 'Kente cloth can be made from various materials including cotton, silk, and wool.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-045',
    type: 'mcq',
    question: 'What is the traditional Ghanaian woven cloth called?',
    options: ['Kente', 'Batik', 'Tie-dye', 'Print'],
    correctAnswer: 0,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Crafts',
    explanation: 'Kente is a colorful woven cloth traditionally made by the Akan people of Ghana.',
    source: 'practice',
    year: 2019,
  },

  // ============================================
  // Additional BECE Creative Arts Questions
  // ============================================

  // Visual Arts - More Concepts
  {
    id: 'jhs-ca-046',
    type: 'mcq',
    question: 'What is the art of printing designs on fabric called?',
    options: ['Weaving', 'Batik', 'Pottery', 'Carving'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Crafts',
    explanation: 'Batik involves using wax and dye to create patterns on fabric.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-047',
    type: 'mcq',
    question: 'What is a self-portrait?',
    options: ['A picture of someone else', 'A picture of yourself', 'A landscape', 'A still life'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'A self-portrait is a drawing or painting of the artist by themselves.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-048',
    type: 'mcq',
    question: 'What is a picture of natural scenery called?',
    options: ['Portrait', 'Still life', 'Landscape', 'Abstract'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'A landscape shows natural scenery like mountains, rivers, or fields.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ca-049',
    type: 'mcq',
    question: 'What is a picture of objects like fruits or flowers called?',
    options: ['Portrait', 'Still life', 'Landscape', 'Abstract'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Still life shows inanimate objects like fruits, flowers, or vases.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-050',
    type: 'mcq',
    question: 'What is the technique of creating images using small colored pieces called?',
    options: ['Collage', 'Mosaic', 'Painting', 'Drawing'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Mosaic uses small pieces of colored glass, stone, or tile to create images.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-051',
    type: 'mcq',
    question: 'What is the art of creating images by pressing ink onto paper called?',
    options: ['Drawing', 'Painting', 'Printmaking', 'Sculpture'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Printmaking involves creating images by transferring ink from a surface to paper.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ca-052',
    type: 'mcq',
    question: 'What is the technique of creating art without recognizable objects called?',
    options: ['Realism', 'Abstract', 'Impressionism', 'Portrait'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Abstract art uses shapes, colors, and forms without representing recognizable objects.',
    source: 'practice',
    year: 2021,
  },

  // Music - More Concepts
  {
    id: 'jhs-ca-053',
    type: 'mcq',
    question: 'What is the pattern of beats in music called?',
    options: ['Tempo', 'Pitch', 'Rhythm', 'Volume'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Music',
    explanation: 'Rhythm is the pattern of sounds and silences in music.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-054',
    type: 'mcq',
    question: 'What is the loudness or softness of music called?',
    options: ['Pitch', 'Tempo', 'Volume', 'Rhythm'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Music',
    explanation: 'Volume (or dynamics) refers to how loud or soft music is.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ca-055',
    type: 'mcq',
    question: 'What is a person who writes music called?',
    options: ['Musician', 'Composer', 'Conductor', 'Singer'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Music',
    explanation: 'A composer creates original musical pieces.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-056',
    type: 'mcq',
    question: 'What is a person who leads an orchestra called?',
    options: ['Musician', 'Composer', 'Conductor', 'Singer'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Music',
    explanation: 'A conductor leads and directs an orchestra during performances.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-057',
    type: 'mcq',
    question: 'What is a performance by one person called?',
    options: ['Duet', 'Solo', 'Trio', 'Quartet'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Music',
    explanation: 'A solo is a musical performance by a single person.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ca-058',
    type: 'mcq',
    question: 'Which traditional Ghanaian instrument is a type of xylophone?',
    options: ['Fontomfrom', 'Atumpan', 'Gyil', 'Kora'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Music',
    explanation: 'Gyil is a traditional Ghanaian xylophone made of wood and gourds.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-059',
    type: 'mcq',
    question: 'What is the main melody in a song called?',
    options: ['Harmony', 'Tune', 'Beat', 'Rhythm'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Music',
    explanation: 'The tune (or melody) is the main sequence of notes in a song.',
    source: 'practice',
    year: 2020,
  },

  // Drama - More Concepts
  {
    id: 'jhs-ca-060',
    type: 'mcq',
    question: 'What are the items used on stage to create a setting called?',
    options: ['Costumes', 'Props', 'Scripts', 'Lights'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Drama',
    explanation: 'Props (properties) are objects used on stage during a performance.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-061',
    type: 'mcq',
    question: 'What are the clothes worn by actors called?',
    options: ['Props', 'Costumes', 'Uniforms', 'Dresses'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Drama',
    explanation: 'Costumes are the clothing worn by actors to represent their characters.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-062',
    type: 'mcq',
    question: 'What is a short play with a moral lesson called?',
    options: ['Comedy', 'Tragedy', 'Fable', 'Drama'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Drama',
    explanation: 'A fable is a short story or play that teaches a moral lesson.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ca-063',
    type: 'mcq',
    question: 'What is a play that makes people laugh called?',
    options: ['Tragedy', 'Comedy', 'Drama', 'Fable'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Drama',
    explanation: 'Comedy is a type of play intended to be humorous and make people laugh.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-064',
    type: 'mcq',
    question: 'What is a play with a sad ending called?',
    options: ['Comedy', 'Tragedy', 'Fable', 'Drama'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Drama',
    explanation: 'Tragedy is a type of play that deals with serious themes and often has a sad ending.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-065',
    type: 'mcq',
    question: 'What is the area behind the stage where actors prepare called?',
    options: ['Stage', 'Audience', 'Backstage', 'Lobby'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Drama',
    explanation: 'Backstage is the area behind the stage where actors prepare and props are stored.',
    source: 'practice',
    year: 2019,
  },

  // Dance - More Concepts
  {
    id: 'jhs-ca-066',
    type: 'mcq',
    question: 'What is the traditional dance of the Ga people called?',
    options: ['Adowa', 'Kpanlogo', 'Bamaya', 'Agbadza'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Dance',
    explanation: 'Kpanlogo is a popular traditional dance of the Ga people of Ghana.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-067',
    type: 'mcq',
    question: 'What is the traditional dance of the Dagomba people called?',
    options: ['Adowa', 'Kpanlogo', 'Bamaya', 'Agbadza'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Dance',
    explanation: 'Bamaya is a traditional dance of the Dagomba people in northern Ghana.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-068',
    type: 'mcq',
    question: 'What is the traditional dance of the Ewe people called?',
    options: ['Adowa', 'Kpanlogo', 'Bamaya', 'Agbadza'],
    correctAnswer: 3,
    subject: 'Creative Arts',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Dance',
    explanation: 'Agbadza is a traditional dance of the Ewe people of Ghana and Togo.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ca-069',
    type: 'mcq',
    question: 'What is the movement of the body to music called?',
    options: ['Singing', 'Dancing', 'Acting', 'Playing'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Dance',
    explanation: 'Dancing is the art of moving the body rhythmically to music.',
    source: 'practice',
    year: 2021,
  },

  // Crafts - More Concepts
  {
    id: 'jhs-ca-070',
    type: 'mcq',
    question: 'What is the art of decorating fabric with patterns using wax and dye called?',
    options: ['Weaving', 'Batik', 'Tie-dye', 'Printing'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Crafts',
    explanation: 'Batik uses wax to resist dye, creating patterns on fabric.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-071',
    type: 'mcq',
    question: 'What is the art of creating patterns by tying fabric before dyeing called?',
    options: ['Batik', 'Tie-dye', 'Weaving', 'Printing'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Crafts',
    explanation: 'Tie-dye involves tying fabric in patterns before applying dye.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ca-072',
    type: 'mcq',
    question: 'What tool is used for weaving?',
    options: ['Brush', 'Loom', 'Chisel', 'Hammer'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Crafts',
    explanation: 'A loom is a device used to weave threads into fabric.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-073',
    type: 'mcq',
    question: 'What is the art of making jewelry called?',
    options: ['Pottery', 'Weaving', 'Jewelry making', 'Carving'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Crafts',
    explanation: 'Jewelry making involves creating decorative items from metals, beads, or stones.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-074',
    type: 'mcq',
    question: 'What material is commonly used for making beads?',
    options: ['Wood', 'Glass', 'Clay', 'All of the above'],
    correctAnswer: 3,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Crafts',
    explanation: 'Beads can be made from various materials including wood, glass, and clay.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ca-075',
    type: 'mcq',
    question: 'What is the art of making decorative objects from paper called?',
    options: ['Origami', 'Collage', 'Paper mache', 'All of the above'],
    correctAnswer: 3,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Crafts',
    explanation: 'Origami, collage, and paper mache are all paper-based art forms.',
    source: 'practice',
    year: 2021,
  },
];

