// JHS Social Studies Questions
// BECE-level questions migrated to modular ChallengeQuestion format
// NOTE: These are practice-style BECE-level questions, not yet tagged as verified past questions.

import type { ChallengeQuestion } from '../types';

export const jhsSocialStudiesQuestions: ChallengeQuestion[] = [
  // ============================================
  // MCQ Questions (Initial Batch)
  // ============================================

  // JHS Social Studies - Geography
  {
    id: 'jhs-soc-001',
    type: 'mcq',
    question: 'The capital city of Ghana is...',
    options: ['Kumasi', 'Accra', 'Tamale', 'Cape Coast'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Geography',
    explanation: 'Accra is the capital.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-002',
    type: 'mcq',
    question: 'The highest mountain in Ghana is...',
    options: ['Mt. Everest', 'Mt. Afadja', 'Mt. Kilimanjaro', 'Mt. Sinai'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Geography',
    explanation: 'Mount Afadja (Afadjato).',
    source: 'practice',
    year: 2017,
  },
  {
    id: 'jhs-soc-003',
    type: 'mcq',
    question: 'Which region of Ghana is known for gold mining?',
    options: ['Northern Region', 'Ashanti Region', 'Western Region', 'Eastern Region'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Geography',
    explanation: 'Western Region has major gold mining activities.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-soc-004',
    type: 'mcq',
    question: 'The largest lake in Ghana is...',
    options: ['Lake Bosomtwe', 'Lake Volta', 'Lake Chad', 'Lake Tanganyika'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Geography',
    explanation: 'Lake Volta is the largest man-made lake in Ghana.',
    source: 'practice',
    year: 2021,
  },

  // JHS Social Studies - History
  {
    id: 'jhs-soc-005',
    type: 'mcq',
    question: 'Ghana became independent in...',
    options: ['1957', '1960', '1966', '1992'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'History',
    explanation: 'March 6, 1957.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-soc-006',
    type: 'mcq',
    question: 'The first President of Ghana was...',
    options: ['J.J. Rawlings', 'K.A. Busia', 'Kwame Nkrumah', 'J.A. Kufuor'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'History',
    explanation: 'Dr. Kwame Nkrumah was the first President.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-007',
    type: 'mcq',
    question: 'Ghana became a republic in...',
    options: ['1957', '1960', '1966', '1992'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'History',
    explanation: 'Ghana became a republic on July 1, 1960.',
    source: 'practice',
    year: 2018,
  },

  // JHS Social Studies - Economics
  {
    id: 'jhs-soc-008',
    type: 'mcq',
    question: 'Which of these is a primary product?',
    options: ['Cocoa', 'Chocolate', 'Cloth', 'Furniture'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Economics',
    explanation: 'Cocoa is a raw material.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-soc-009',
    type: 'mcq',
    question: 'The main cash crop of Ghana is...',
    options: ['Maize', 'Cocoa', 'Yam', 'Cassava'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Economics',
    explanation: 'Cocoa is the major export crop.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-010',
    type: 'mcq',
    question: 'The currency of Ghana is...',
    options: ['Cedi', 'Dollar', 'Pound', 'Euro'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Economics',
    explanation: 'Ghana uses the Ghana Cedi (GHS).',
    source: 'practice',
    year: 2022,
  },

  // JHS Social Studies - Citizenship & Government
  {
    id: 'jhs-soc-011',
    type: 'mcq',
    question: 'The head of the family is the...',
    options: ['Mother', 'Father', 'Uncle', 'Grandfather'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Citizenship',
    explanation: 'Traditionally, the father heads the nuclear family.',
    source: 'practice',
    year: 2018,
  },
  {
    id: 'jhs-soc-012',
    type: 'mcq',
    question: 'Which of the following is a function of the police?',
    options: ['Making laws', 'Interpreting laws', 'Maintaining law and order', 'Judging criminals'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Government',
    explanation: 'Police enforce laws.',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-soc-013',
    type: 'mcq',
    question: 'The constitution of Ghana is the...',
    options: ['Supreme law', 'Ordinary law', 'Customary law', 'Decree'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Government',
    explanation: 'It is the highest law of the land.',
    source: 'practice',
    year: 2016,
  },
  {
    id: 'jhs-soc-014',
    type: 'mcq',
    question: 'Adolescence is the period between...',
    options: ['Childhood and adulthood', 'Birth and childhood', 'Adulthood and old age', 'Infancy and childhood'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Citizenship',
    explanation: 'Transition period.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-soc-015',
    type: 'mcq',
    question: 'Which of these is an environmental problem?',
    options: ['Afforestation', 'Pollution', 'Recycling', 'Conservation'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Environment',
    explanation: 'Pollution harms the environment.',
    source: 'practice',
    year: 2015,
  },

  // ============================================
  // Additional Questions (Batch 1)
  // ============================================

  // JHS Social Studies - Hard (JHS 3)
  {
    id: 'jhs-soc-016',
    type: 'mcq',
    question: 'The three arms of government are...',
    options: ['Executive, Legislature, Judiciary', 'President, Parliament, Courts', 'Ministry, Assembly, Police', 'Executive, Military, Police'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Government',
    explanation: 'Separation of powers ensures checks and balances.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-017',
    type: 'mcq',
    question: 'Which of the following is a right of a citizen?',
    options: ['To pay taxes', 'To vote', 'To break laws', 'To avoid responsibilities'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Citizenship',
    explanation: 'Voting is a fundamental right of citizens.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-soc-018',
    type: 'mcq',
    question: 'The main export of Ghana is...',
    options: ['Gold', 'Cocoa', 'Oil', 'Diamonds'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Economics',
    explanation: 'Gold is Ghana\'s largest export by value.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-soc-019',
    type: 'mcq',
    question: 'Which of these is a responsibility of a citizen?',
    options: ['To demand rights only', 'To pay taxes', 'To avoid voting', 'To break laws'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Citizenship',
    explanation: 'Paying taxes is a civic responsibility.',
    source: 'practice',
    year: 2018,
  },
  {
    id: 'jhs-soc-020',
    type: 'mcq',
    question: 'The main cause of deforestation in Ghana is...',
    options: ['Natural disasters', 'Illegal logging', 'Wildlife', 'Rainfall'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Environment',
    explanation: 'Illegal logging and farming are major causes.',
    source: 'practice',
    year: 2022,
  },

  // ============================================
  // Additional BECE Social Studies Questions (Batch 2)
  // ============================================

  // JHS Social Studies - More Geography
  {
    id: 'jhs-soc-021',
    type: 'mcq',
    question: 'Which region of Ghana is known as the "Garden City"?',
    options: ['Greater Accra', 'Ashanti Region', 'Eastern Region', 'Central Region'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Geography',
    explanation: 'Greater Accra, particularly Accra, is known as the Garden City.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-soc-022',
    type: 'mcq',
    question: 'The longest river in Ghana is...',
    options: ['River Pra', 'River Volta', 'River Tano', 'River Ankobra'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Geography',
    explanation: 'River Volta is the longest river in Ghana.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-023',
    type: 'mcq',
    question: 'Which of these is a coastal region in Ghana?',
    options: ['Northern Region', 'Upper East Region', 'Central Region', 'Brong Ahafo Region'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Geography',
    explanation: 'Central Region is located along the coast of Ghana.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-soc-024',
    type: 'mcq',
    question: 'The Volta Region was created in...',
    options: ['1957', '1960', '1983', '1992'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Geography',
    explanation: 'Volta Region was created in 1983.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-025',
    type: 'mcq',
    question: 'Which region is known for diamond mining?',
    options: ['Western Region', 'Eastern Region', 'Ashanti Region', 'Northern Region'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Geography',
    explanation: 'Eastern Region has diamond mining activities.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-soc-026',
    type: 'mcq',
    question: 'The climate of Ghana is...',
    options: ['Tropical', 'Temperate', 'Desert', 'Arctic'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Geography',
    explanation: 'Ghana has a tropical climate with wet and dry seasons.',
    source: 'practice',
    year: 2020,
  },

  // JHS Social Studies - More History
  {
    id: 'jhs-soc-027',
    type: 'mcq',
    question: 'The name "Ghana" was chosen because...',
    options: ['It was the name of an ancient empire', 'It means gold', 'It was the first president\'s name', 'It means freedom'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'History',
    explanation: 'Ghana was named after the ancient Ghana Empire in West Africa.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-soc-028',
    type: 'mcq',
    question: 'Who led Ghana to independence?',
    options: ['J.B. Danquah', 'Kwame Nkrumah', 'K.A. Busia', 'J.J. Rawlings'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'History',
    explanation: 'Dr. Kwame Nkrumah led the independence movement and became the first Prime Minister and President.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-029',
    type: 'mcq',
    question: 'The first Prime Minister of Ghana was...',
    options: ['J.B. Danquah', 'Kwame Nkrumah', 'K.A. Busia', 'J.A. Kufuor'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'History',
    explanation: 'Kwame Nkrumah was the first Prime Minister before becoming President.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-soc-030',
    type: 'mcq',
    question: 'Ghana was formerly known as...',
    options: ['Gold Coast', 'Ivory Coast', 'Slave Coast', 'Grain Coast'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'History',
    explanation: 'Ghana was called the Gold Coast during colonial times due to its gold resources.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-031',
    type: 'mcq',
    question: 'The first European country to arrive in Ghana was...',
    options: ['Britain', 'Portugal', 'France', 'Germany'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'History',
    explanation: 'Portuguese explorers were the first Europeans to arrive in the Gold Coast in the 15th century.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-soc-032',
    type: 'mcq',
    question: 'The 1992 Constitution of Ghana established...',
    options: ['A military government', 'A one-party state', 'A multi-party democracy', 'A monarchy'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'History',
    explanation: 'The 1992 Constitution established the Fourth Republic with multi-party democracy.',
    source: 'practice',
    year: 2020,
  },

  // JHS Social Studies - More Economics
  {
    id: 'jhs-soc-033',
    type: 'mcq',
    question: 'Which of these is a secondary product?',
    options: ['Cocoa', 'Timber', 'Chocolate', 'Gold'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Economics',
    explanation: 'Chocolate is processed from cocoa, making it a secondary product.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-soc-034',
    type: 'mcq',
    question: 'The main mineral export of Ghana is...',
    options: ['Diamond', 'Bauxite', 'Gold', 'Manganese'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Economics',
    explanation: 'Gold is Ghana\'s largest mineral export by value.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-035',
    type: 'mcq',
    question: 'What is the main source of foreign exchange for Ghana?',
    options: ['Tourism', 'Remittances', 'Exports', 'Foreign aid'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Economics',
    explanation: 'Exports (gold, cocoa, oil) are the main source of foreign exchange.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-soc-036',
    type: 'mcq',
    question: 'Which of these is a tertiary economic activity?',
    options: ['Farming', 'Mining', 'Banking', 'Fishing'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Economics',
    explanation: 'Banking is a service (tertiary) activity. Farming, mining, and fishing are primary activities.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-037',
    type: 'mcq',
    question: 'The process of adding value to raw materials is called...',
    options: ['Extraction', 'Manufacturing', 'Distribution', 'Consumption'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Economics',
    explanation: 'Manufacturing processes raw materials into finished products, adding value.',
    source: 'practice',
    year: 2021,
  },

  // JHS Social Studies - More Government & Citizenship
  {
    id: 'jhs-soc-038',
    type: 'mcq',
    question: 'The head of state in Ghana is the...',
    options: ['Prime Minister', 'President', 'Chief Justice', 'Speaker of Parliament'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Government',
    explanation: 'The President is both head of state and head of government in Ghana.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-039',
    type: 'mcq',
    question: 'The legislative arm of government makes...',
    options: ['Laws', 'Judgments', 'Policies', 'Decisions'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Government',
    explanation: 'The Legislature (Parliament) makes laws.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-soc-040',
    type: 'mcq',
    question: 'The judiciary interprets and...',
    options: ['Makes laws', 'Enforces laws', 'Applies laws', 'Creates policies'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Government',
    explanation: 'The Judiciary interprets and applies laws through the courts.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-041',
    type: 'mcq',
    question: 'Which of these is a civic responsibility?',
    options: ['Voting', 'Demanding rights only', 'Breaking laws', 'Avoiding taxes'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Citizenship',
    explanation: 'Voting is both a right and a responsibility of citizens.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-soc-042',
    type: 'mcq',
    question: 'The age at which one can vote in Ghana is...',
    options: ['16 years', '17 years', '18 years', '21 years'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Citizenship',
    explanation: 'The voting age in Ghana is 18 years.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-043',
    type: 'mcq',
    question: 'Separation of powers prevents...',
    options: ['Democracy', 'Dictatorship', 'Development', 'Voting'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Government',
    explanation: 'Separation of powers prevents one arm of government from becoming too powerful (dictatorship).',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-soc-044',
    type: 'mcq',
    question: 'Which of these is a fundamental human right?',
    options: ['Right to break laws', 'Right to freedom of speech', 'Right to avoid taxes', 'Right to harm others'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Citizenship',
    explanation: 'Freedom of speech is a fundamental human right guaranteed by the constitution.',
    source: 'practice',
    year: 2020,
  },

  // JHS Social Studies - More Environment
  {
    id: 'jhs-soc-045',
    type: 'mcq',
    question: 'Which of these helps protect the environment?',
    options: ['Deforestation', 'Pollution', 'Afforestation', 'Littering'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Environment',
    explanation: 'Afforestation (planting trees) helps protect and restore the environment.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-soc-046',
    type: 'mcq',
    question: 'The main cause of air pollution in cities is...',
    options: ['Trees', 'Vehicles', 'Rain', 'Wind'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Environment',
    explanation: 'Vehicle emissions are a major source of air pollution in urban areas.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-047',
    type: 'mcq',
    question: 'Which of these is a renewable resource?',
    options: ['Coal', 'Petroleum', 'Solar energy', 'Natural gas'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Environment',
    explanation: 'Solar energy is renewable and can be replenished naturally.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-soc-048',
    type: 'mcq',
    question: 'What is the main cause of water pollution?',
    options: ['Rain', 'Industrial waste', 'Evaporation', 'Condensation'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Environment',
    explanation: 'Industrial waste and sewage are major causes of water pollution.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-049',
    type: 'mcq',
    question: 'The practice of using resources wisely is called...',
    options: ['Waste', 'Conservation', 'Pollution', 'Destruction'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Environment',
    explanation: 'Conservation means using resources wisely to ensure they last for future generations.',
    source: 'practice',
    year: 2021,
  },

  // JHS Social Studies - Culture & Society
  {
    id: 'jhs-soc-050',
    type: 'mcq',
    question: 'Which of these is a traditional festival in Ghana?',
    options: ['Christmas', 'Easter', 'Hogbetsotso', 'New Year'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Culture',
    explanation: 'Hogbetsotso is a traditional festival celebrated by the Anlo people in the Volta Region.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-051',
    type: 'mcq',
    question: 'The main language spoken in Ghana is...',
    options: ['French', 'English', 'Portuguese', 'Spanish'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Culture',
    explanation: 'English is the official language of Ghana, inherited from colonial times.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-soc-052',
    type: 'mcq',
    question: 'Which of these is a major ethnic group in Ghana?',
    options: ['Yoruba', 'Zulu', 'Akan', 'Hausa'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Culture',
    explanation: 'The Akan is one of the largest ethnic groups in Ghana.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-053',
    type: 'mcq',
    question: 'The traditional system of governance in Ghana is called...',
    options: ['Democracy', 'Chieftaincy', 'Republic', 'Monarchy'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Culture',
    explanation: 'The chieftaincy system is the traditional governance system in Ghana.',
    source: 'practice',
    year: 2021,
  },

  // JHS Social Studies - More Advanced Topics
  {
    id: 'jhs-soc-054',
    type: 'mcq',
    question: 'Productivity is defined as...',
    options: ['Output per unit input', 'Total production', 'Cost of production', 'Profit made'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Economics',
    explanation: 'Productivity measures efficiency - output per unit of input.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-055',
    type: 'mcq',
    question: 'Which of these is a feature of a good map?',
    options: ['Title', 'Color only', 'Size only', 'Shape only'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Geography',
    explanation: 'A good map must have a title, scale, key/legend, and compass direction.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-soc-056',
    type: 'mcq',
    question: 'Globalization has made the world a...',
    options: ['Big continent', 'Global village', 'Small country', 'Large market'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Global Issues',
    explanation: 'Globalization refers to the interconnectedness of the world, making it a "global village".',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-057',
    type: 'mcq',
    question: 'The process of people moving from rural to urban areas is called...',
    options: ['Migration', 'Urbanization', 'Emigration', 'Immigration'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Geography',
    explanation: 'Urbanization is the movement of people from rural to urban areas.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-soc-058',
    type: 'mcq',
    question: 'Which organization promotes peace and cooperation in West Africa?',
    options: ['UN', 'AU', 'ECOWAS', 'EU'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Global Issues',
    explanation: 'ECOWAS (Economic Community of West African States) promotes regional cooperation.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-059',
    type: 'mcq',
    question: 'The main purpose of the United Nations is to...',
    options: ['Control countries', 'Promote world peace', 'Make money', 'Conquer nations'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Global Issues',
    explanation: 'The UN was established to promote international peace and security.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-soc-060',
    type: 'mcq',
    question: 'Which of these is a natural resource?',
    options: ['Car', 'Computer', 'Water', 'Television'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Geography',
    explanation: 'Water is a natural resource found in nature. Others are manufactured products.',
    source: 'practice',
    year: 2020,
  },

  // ============================================
  // Additional BECE Social Studies Questions (Batch 3)
  // ============================================

  // JHS Social Studies - More Geography
  {
    id: 'jhs-soc-061',
    type: 'mcq',
    question: 'Which region is the largest in Ghana?',
    options: ['Northern Region', 'Ashanti Region', 'Western Region', 'Eastern Region'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Geography',
    explanation: 'Northern Region is the largest region in Ghana by land area.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-soc-062',
    type: 'mcq',
    question: 'The main port city of Ghana is...',
    options: ['Accra', 'Tema', 'Takoradi', 'Cape Coast'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Geography',
    explanation: 'Tema is Ghana\'s main port city and industrial hub.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-063',
    type: 'mcq',
    question: 'Which of these is a landlocked region in Ghana?',
    options: ['Greater Accra', 'Central Region', 'Upper East Region', 'Western Region'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Geography',
    explanation: 'Upper East Region is landlocked (no coastline).',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-soc-064',
    type: 'mcq',
    question: 'The vegetation type in northern Ghana is mainly...',
    options: ['Rainforest', 'Savanna', 'Desert', 'Tundra'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Geography',
    explanation: 'Northern Ghana has savanna vegetation with grasslands and scattered trees.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-065',
    type: 'mcq',
    question: 'Which region shares a border with Togo?',
    options: ['Western Region', 'Volta Region', 'Central Region', 'Ashanti Region'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Geography',
    explanation: 'Volta Region shares an eastern border with Togo.',
    source: 'practice',
    year: 2021,
  },

  // JHS Social Studies - More History
  {
    id: 'jhs-soc-066',
    type: 'mcq',
    question: 'The first university in Ghana is...',
    options: ['University of Ghana', 'KNUST', 'University of Cape Coast', 'University of Education'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'History',
    explanation: 'University of Ghana, Legon, was established in 1948 as the first university.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-067',
    type: 'mcq',
    question: 'The period of military rule in Ghana is called...',
    options: ['Democracy', 'Republic', 'Coup d\'état', 'Constitution'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'History',
    explanation: 'Coup d\'état refers to the overthrow of government by military force.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-soc-068',
    type: 'mcq',
    question: 'The Big Six were leaders of...',
    options: ['The military', 'The independence movement', 'The judiciary', 'The police'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'History',
    explanation: 'The Big Six were key leaders in Ghana\'s independence struggle.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-069',
    type: 'mcq',
    question: 'Ghana\'s first republic lasted from...',
    options: ['1957-1960', '1960-1966', '1966-1979', '1992-present'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'History',
    explanation: 'First Republic: 1960-1966 (ended by military coup).',
    source: 'practice',
    year: 2021,
  },

  // JHS Social Studies - More Economics
  {
    id: 'jhs-soc-070',
    type: 'mcq',
    question: 'The main agricultural product of Ghana is...',
    options: ['Rice', 'Cocoa', 'Wheat', 'Cotton'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Economics',
    explanation: 'Cocoa is Ghana\'s main agricultural export product.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-071',
    type: 'mcq',
    question: 'Which of these is a non-renewable resource?',
    options: ['Water', 'Solar energy', 'Gold', 'Wind'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Economics',
    explanation: 'Gold is a non-renewable resource - once mined, it cannot be replaced.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-soc-072',
    type: 'mcq',
    question: 'The exchange of goods and services is called...',
    options: ['Production', 'Trade', 'Consumption', 'Distribution'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Economics',
    explanation: 'Trade is the buying and selling of goods and services.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-073',
    type: 'mcq',
    question: 'Which of these is a primary economic activity?',
    options: ['Banking', 'Teaching', 'Farming', 'Trading'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Economics',
    explanation: 'Farming is a primary activity (extracting/producing raw materials).',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-soc-074',
    type: 'mcq',
    question: 'The difference between exports and imports is called...',
    options: ['Balance of trade', 'Balance of payment', 'Profit', 'Loss'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Economics',
    explanation: 'Balance of trade is the difference between a country\'s exports and imports.',
    source: 'practice',
    year: 2020,
  },

  // JHS Social Studies - More Government
  {
    id: 'jhs-soc-075',
    type: 'mcq',
    question: 'The number of regions in Ghana is...',
    options: ['10', '14', '16', '18'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Government',
    explanation: 'Ghana currently has 16 administrative regions.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-soc-076',
    type: 'mcq',
    question: 'The local government system in Ghana is called...',
    options: ['Parliament', 'Assembly', 'Court', 'Ministry'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Government',
    explanation: 'District/Municipal/Metropolitan Assemblies are the local government units.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-077',
    type: 'mcq',
    question: 'The head of a district assembly is called...',
    options: ['Mayor', 'District Chief Executive', 'Governor', 'Commissioner'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Government',
    explanation: 'District Chief Executive (DCE) heads the district assembly.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-soc-078',
    type: 'mcq',
    question: 'Which arm of government enforces laws?',
    options: ['Legislature', 'Executive', 'Judiciary', 'Police'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Government',
    explanation: 'The Executive (President, Ministers) enforces laws through government agencies.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-079',
    type: 'mcq',
    question: 'The highest court in Ghana is the...',
    options: ['High Court', 'Circuit Court', 'Supreme Court', 'District Court'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Government',
    explanation: 'The Supreme Court is the highest court and final court of appeal.',
    source: 'practice',
    year: 2021,
  },

  // JHS Social Studies - More Citizenship
  {
    id: 'jhs-soc-080',
    type: 'mcq',
    question: 'Which of these is NOT a right of a citizen?',
    options: ['Right to education', 'Right to break laws', 'Right to vote', 'Right to freedom of speech'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Citizenship',
    explanation: 'Citizens do not have the right to break laws. They must obey laws.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-081',
    type: 'mcq',
    question: 'The process of becoming a citizen of a country is called...',
    options: ['Naturalization', 'Migration', 'Emigration', 'Immigration'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Citizenship',
    explanation: 'Naturalization is the legal process of acquiring citizenship.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-soc-082',
    type: 'mcq',
    question: 'Which of these is a civic duty?',
    options: ['Demanding rights only', 'Obeying laws', 'Breaking rules', 'Avoiding responsibilities'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Citizenship',
    explanation: 'Obeying laws is a fundamental civic duty of all citizens.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-083',
    type: 'mcq',
    question: 'A person who moves to another country to live is called...',
    options: ['Emigrant', 'Immigrant', 'Refugee', 'Tourist'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Citizenship',
    explanation: 'An emigrant leaves their country; an immigrant enters a new country.',
    source: 'practice',
    year: 2021,
  },

  // JHS Social Studies - More Environment & Development
  {
    id: 'jhs-soc-084',
    type: 'mcq',
    question: 'Which of these causes soil erosion?',
    options: ['Planting trees', 'Deforestation', 'Afforestation', 'Conservation'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Environment',
    explanation: 'Deforestation removes tree cover, leading to soil erosion.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-085',
    type: 'mcq',
    question: 'The practice of growing different crops on the same land is called...',
    options: ['Monoculture', 'Crop rotation', 'Deforestation', 'Overgrazing'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Environment',
    explanation: 'Crop rotation helps maintain soil fertility by alternating crops.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-soc-086',
    type: 'mcq',
    question: 'Which of these is a sustainable development practice?',
    options: ['Overfishing', 'Deforestation', 'Recycling', 'Pollution'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Environment',
    explanation: 'Recycling conserves resources and reduces waste, supporting sustainability.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-087',
    type: 'mcq',
    question: 'The main cause of climate change is...',
    options: ['Natural cycles', 'Human activities', 'Ocean currents', 'Wind patterns'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Environment',
    explanation: 'Human activities like burning fossil fuels are the main cause of climate change.',
    source: 'practice',
    year: 2021,
  },

  // JHS Social Studies - More Culture & Traditions
  {
    id: 'jhs-soc-088',
    type: 'mcq',
    question: 'Which festival is celebrated by the Ashanti people?',
    options: ['Hogbetsotso', 'Aboakyer', 'Akwasidae', 'Homowo'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Culture',
    explanation: 'Akwasidae is a major festival of the Ashanti people.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-089',
    type: 'mcq',
    question: 'The traditional cloth of Ghana is called...',
    options: ['Kente', 'Cotton', 'Silk', 'Linen'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Culture',
    explanation: 'Kente is the traditional handwoven cloth of Ghana, especially the Ashanti and Ewe.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-soc-090',
    type: 'mcq',
    question: 'Which of these is a traditional dance in Ghana?',
    options: ['Hip-hop', 'Jazz', 'Adowa', 'Ballet'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Culture',
    explanation: 'Adowa is a traditional dance of the Ashanti people of Ghana.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-091',
    type: 'mcq',
    question: 'The traditional ruler in Ghana is called...',
    options: ['President', 'Chief', 'Governor', 'Mayor'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Culture',
    explanation: 'Chiefs are traditional rulers in Ghana\'s chieftaincy system.',
    source: 'practice',
    year: 2021,
  },

  // JHS Social Studies - More Global Issues
  {
    id: 'jhs-soc-092',
    type: 'mcq',
    question: 'The African Union (AU) promotes...',
    options: ['Division', 'Unity and cooperation', 'War', 'Conflict'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Global Issues',
    explanation: 'The AU promotes unity, cooperation, and development among African countries.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-093',
    type: 'mcq',
    question: 'Which of these is a problem of urbanization?',
    options: ['Better healthcare', 'Overcrowding', 'More jobs', 'Better education'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Geography',
    explanation: 'Overcrowding is a major problem of rapid urbanization.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-soc-094',
    type: 'mcq',
    question: 'The movement of people from one place to another is called...',
    options: ['Migration', 'Stationary', 'Settlement', 'Residence'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Geography',
    explanation: 'Migration is the movement of people from one place to another.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-095',
    type: 'mcq',
    question: 'Which of these is a benefit of trade?',
    options: ['War', 'Economic growth', 'Conflict', 'Division'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Economics',
    explanation: 'Trade promotes economic growth by allowing countries to specialize and exchange goods.',
    source: 'practice',
    year: 2021,
  },
];

