// Biology Questions for SHS
// All 100 actual WASSCE questions migrated to new format with mixed question types
import type { ChallengeQuestion } from '../types';

export const biologyQuestions: ChallengeQuestion[] = [
  // ============================================
  // MCQ Questions (Majority - 75 questions)
  // ============================================
  
  // Biology - Cell Biology (Actual WASSCE)
  {
    id: 'wassce-2023-bio-001',
    type: 'mcq',
    question: 'Which organelle is known as the "powerhouse of the cell"?',
    options: ['Nucleus', 'Mitochondria', 'Ribosome', 'Endoplasmic reticulum'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Cell Biology',
    explanation: 'Mitochondria are called the powerhouse because they produce ATP (energy) through cellular respiration',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-bio-002',
    type: 'mcq',
    question: 'What is the function of the nucleus?',
    options: ['Produce energy', 'Control cell activities and store genetic material', 'Synthesize proteins', 'Transport materials'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Cell Biology',
    explanation: 'The nucleus contains DNA (genetic material) and controls all cell activities',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-bio-003',
    type: 'mcq',
    question: 'Which organelle is responsible for protein synthesis?',
    options: ['Mitochondria', 'Ribosome', 'Golgi apparatus', 'Lysosome'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Cell Biology',
    explanation: 'Ribosomes are the sites of protein synthesis, where mRNA is translated into proteins',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-bio-004',
    type: 'mcq',
    question: 'What is the main difference between plant and animal cells?',
    options: ['Plant cells have mitochondria', 'Plant cells have cell walls and chloroplasts', 'Animal cells have nuclei', 'Animal cells are larger'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Cell Biology',
    explanation: 'Plant cells have rigid cell walls (cellulose) and chloroplasts for photosynthesis, which animal cells lack',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-bio-005',
    type: 'mcq',
    question: 'What is the function of the cell membrane?',
    options: ['Control cell activities', 'Control what enters and leaves the cell', 'Produce energy', 'Store genetic material'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Cell Biology',
    explanation: 'The cell membrane is selectively permeable, controlling the movement of substances in and out of the cell',
    source: 'actual WASSCE',
    year: 2019
  },
  {
    id: 'wassce-2023-bio-006',
    type: 'fill-blank',
    questionTemplate: '{{0}} is the passive movement of water molecules from a region of high water concentration to low water concentration through a semi-permeable membrane.',
    blanks: [
      {
        position: 0,
        correctAnswer: 'Osmosis',
        alternatives: ['osmosis', 'OSMOSIS']
      }
    ],
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Cell Biology',
    explanation: 'Osmosis is the passive movement of water molecules from a region of high water concentration to low water concentration through a semi-permeable membrane',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-bio-007',
    type: 'true-false',
    question: 'Diffusion is the passive movement of particles from a region of high concentration to low concentration.',
    correctAnswer: true,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Cell Biology',
    explanation: 'Diffusion is the passive movement of particles from a region of high concentration to low concentration until equilibrium is reached',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-bio-008',
    type: 'mcq',
    question: 'What is the function of chloroplasts?',
    options: ['Cellular respiration', 'Photosynthesis', 'Protein synthesis', 'Storage'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Cell Biology',
    explanation: 'Chloroplasts contain chlorophyll and are the site of photosynthesis, where plants make food using light energy',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-bio-009',
    type: 'mcq',
    question: 'What is the function of the Golgi apparatus?',
    options: ['Produce energy', 'Modify, package, and transport proteins', 'Synthesize proteins', 'Store genetic material'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Cell Biology',
    explanation: 'The Golgi apparatus modifies, packages, and transports proteins and lipids to their destinations',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-bio-010',
    type: 'short-answer',
    question: 'What is the function of lysosomes?',
    correctAnswer: 'digest cellular waste',
    acceptableAnswers: ['Digest cellular waste', 'Digest waste', 'Break down waste', 'Digest cellular waste and foreign materials'],
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Cell Biology',
    explanation: 'Lysosomes contain digestive enzymes that break down cellular waste, damaged organelles, and foreign materials',
    source: 'actual WASSCE',
    year: 2019,
    maxLength: 50
  },

  // Biology - Human Biology - Circulatory System (Actual WASSCE)
  {
    id: 'wassce-2023-bio-011',
    type: 'mcq',
    question: 'Which blood vessel carries blood away from the heart?',
    options: ['Vein', 'Artery', 'Capillary', 'Venule'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Circulatory System',
    explanation: 'Arteries carry oxygenated blood away from the heart to body tissues (except pulmonary artery)',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-bio-012',
    type: 'mcq',
    question: 'Which blood vessel carries blood back to the heart?',
    options: ['Artery', 'Vein', 'Capillary', 'Arteriole'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Circulatory System',
    explanation: 'Veins carry deoxygenated blood back to the heart (except pulmonary vein which carries oxygenated blood)',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-bio-013',
    type: 'mcq',
    question: 'What is the function of red blood cells?',
    options: ['Fight infections', 'Transport oxygen', 'Clot blood', 'Produce antibodies'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Circulatory System',
    explanation: 'Red blood cells contain hemoglobin which binds and transports oxygen from lungs to body tissues',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-bio-014',
    type: 'mcq',
    question: 'What is the function of white blood cells?',
    options: ['Transport oxygen', 'Fight infections and defend against pathogens', 'Clot blood', 'Transport nutrients'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Immune System',
    explanation: 'White blood cells (leukocytes) defend the body against infections, pathogens, and foreign substances',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-bio-015',
    type: 'true-false',
    question: 'Platelets are involved in blood clotting to prevent excessive bleeding.',
    correctAnswer: true,
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Circulatory System',
    explanation: 'Platelets (thrombocytes) are involved in blood clotting (hemostasis) to prevent excessive bleeding',
    source: 'actual WASSCE',
    year: 2019
  },
  {
    id: 'wassce-2023-bio-016',
    type: 'fill-blank',
    questionTemplate: 'The human heart has {{0}} chambers.',
    blanks: [
      {
        position: 0,
        correctAnswer: '4',
        alternatives: ['four', 'four chambers']
      }
    ],
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Circulatory System',
    explanation: 'The human heart has 4 chambers: 2 atria (upper) and 2 ventricles (lower)',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-bio-017',
    type: 'mcq',
    question: 'What is the function of the heart?',
    options: ['Filter blood', 'Pump blood throughout the body', 'Store blood', 'Produce blood cells'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Circulatory System',
    explanation: 'The heart pumps blood through the circulatory system, delivering oxygen and nutrients to all body parts',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-bio-018',
    type: 'mcq',
    question: 'Which type of blood vessel has the thinnest walls?',
    options: ['Artery', 'Vein', 'Capillary', 'Arteriole'],
    correctAnswer: 2,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Circulatory System',
    explanation: 'Capillaries have very thin walls (one cell thick) to allow efficient exchange of materials with tissues',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-bio-019',
    type: 'short-answer',
    question: 'What is the largest artery in the human body?',
    correctAnswer: 'aorta',
    acceptableAnswers: ['Aorta', 'AORTA'],
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Circulatory System',
    explanation: 'The aorta is the largest artery, carrying oxygenated blood from the left ventricle to the body',
    source: 'actual WASSCE',
    year: 2020,
    maxLength: 10
  },
  {
    id: 'wassce-2019-bio-020',
    type: 'mcq',
    question: 'What is blood pressure?',
    options: ['Force of blood against artery walls', 'Amount of blood in the body', 'Speed of blood flow', 'Volume of blood'],
    correctAnswer: 0,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Circulatory System',
    explanation: 'Blood pressure is the force exerted by blood against the walls of arteries as the heart pumps',
    source: 'actual WASSCE',
    year: 2019
  },

  // Biology - Human Biology - Digestive System (Actual WASSCE)
  {
    id: 'wassce-2023-bio-021',
    type: 'mcq',
    question: 'Where does digestion begin?',
    options: ['Stomach', 'Small intestine', 'Mouth', 'Esophagus'],
    correctAnswer: 2,
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Digestive System',
    explanation: 'Digestion begins in the mouth where teeth break down food mechanically and saliva contains enzymes (amylase) that start chemical digestion',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-bio-022',
    type: 'mcq',
    question: 'What is the main function of the stomach?',
    options: ['Absorb nutrients', 'Produce bile', 'Break down proteins with gastric juice', 'Absorb water'],
    correctAnswer: 2,
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Digestive System',
    explanation: 'The stomach secretes gastric juice containing pepsin and hydrochloric acid to break down proteins',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-bio-023',
    type: 'mcq',
    question: 'Where are nutrients mainly absorbed?',
    options: ['Stomach', 'Small intestine', 'Large intestine', 'Esophagus'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Digestive System',
    explanation: 'The small intestine has villi (finger-like projections) that absorb most nutrients into the bloodstream',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-bio-024',
    type: 'true-false',
    question: 'Bile emulsifies fats, breaking them into smaller droplets for easier digestion.',
    correctAnswer: true,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Digestive System',
    explanation: 'Bile (produced by liver, stored in gallbladder) emulsifies fats, breaking them into smaller droplets for easier digestion',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-bio-025',
    type: 'mcq',
    question: 'Which organ produces insulin?',
    options: ['Liver', 'Pancreas', 'Stomach', 'Kidney'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Endocrine System',
    explanation: 'The pancreas produces insulin, a hormone that regulates blood sugar levels',
    source: 'actual WASSCE',
    year: 2019
  },
  {
    id: 'wassce-2023-bio-026',
    type: 'mcq',
    question: 'What is the function of the large intestine?',
    options: ['Digest proteins', 'Absorb most nutrients', 'Absorb water and form feces', 'Produce enzymes'],
    correctAnswer: 2,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Digestive System',
    explanation: 'The large intestine (colon) absorbs water and electrolytes, and forms and stores feces',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-bio-027',
    type: 'fill-blank',
    questionTemplate: 'The enzyme that breaks down starch in the mouth is {{0}}.',
    blanks: [
      {
        position: 0,
        correctAnswer: 'amylase',
        alternatives: ['Amylase', 'salivary amylase', 'AMYLASE']
      }
    ],
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Digestive System',
    explanation: 'Salivary amylase in the mouth begins breaking down starch (carbohydrates) into simpler sugars',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-bio-028',
    type: 'short-answer',
    question: 'What is the name of the wave-like muscular contractions that push food through the digestive tract?',
    correctAnswer: 'peristalsis',
    acceptableAnswers: ['Peristalsis', 'PERISTALSIS'],
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Digestive System',
    explanation: 'Peristalsis is the wave-like muscular contractions that push food through the digestive tract',
    source: 'actual WASSCE',
    year: 2021,
    maxLength: 20
  },
  {
    id: 'wassce-2020-bio-029',
    type: 'mcq',
    question: 'What is the function of the liver?',
    options: ['Produce digestive enzymes', 'Produce bile, detoxify blood, store glycogen', 'Absorb nutrients', 'Break down proteins'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Digestive System',
    explanation: 'The liver produces bile, detoxifies blood, stores glycogen, and performs many metabolic functions',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-bio-030',
    type: 'mcq',
    question: 'What are villi?',
    options: ['Digestive enzymes', 'Finger-like projections in the small intestine that increase surface area', 'Muscle contractions', 'Blood vessels'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Digestive System',
    explanation: 'Villi are small finger-like projections lining the small intestine that increase surface area for nutrient absorption',
    source: 'actual WASSCE',
    year: 2019
  },

  // Biology - Human Biology - Respiratory System (Actual WASSCE)
  {
    id: 'wassce-2023-bio-031',
    type: 'mcq',
    question: 'What is the main function of the respiratory system?',
    options: ['Transport nutrients', 'Exchange oxygen and carbon dioxide', 'Pump blood', 'Digest food'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Respiratory System',
    explanation: 'The respiratory system exchanges oxygen (O₂) and carbon dioxide (CO₂) between the body and the environment',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-bio-032',
    type: 'mcq',
    question: 'Where does gas exchange occur in the lungs?',
    options: ['Trachea', 'Bronchi', 'Alveoli', 'Bronchioles'],
    correctAnswer: 2,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Respiratory System',
    explanation: 'Gas exchange occurs in the alveoli (tiny air sacs) where oxygen enters blood and carbon dioxide leaves',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-bio-033',
    type: 'mcq',
    question: 'What is the function of the diaphragm?',
    options: ['Filter air', 'Control breathing by contracting and relaxing', 'Produce mucus', 'Warm air'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Respiratory System',
    explanation: 'The diaphragm is a muscle that contracts (flattens) during inhalation and relaxes during exhalation to control breathing',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-bio-034',
    type: 'true-false',
    question: 'During inhalation, the diaphragm contracts and the ribcage expands.',
    correctAnswer: true,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Respiratory System',
    explanation: 'During inhalation, the diaphragm contracts (flattens) and ribcage expands, increasing lung volume and drawing air in',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-bio-035',
    type: 'mcq',
    question: 'What is the function of the trachea?',
    options: ['Exchange gases', 'Carry air to and from the lungs', 'Produce mucus', 'Filter blood'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Respiratory System',
    explanation: 'The trachea (windpipe) carries air from the nose/mouth to the bronchi and lungs',
    source: 'actual WASSCE',
    year: 2019
  },
  {
    id: 'wassce-2023-bio-036',
    type: 'fill-blank',
    questionTemplate: 'The waste product of respiration is {{0}}.',
    blanks: [
      {
        position: 0,
        correctAnswer: 'carbon dioxide',
        alternatives: ['CO₂', 'CO2', 'Carbon dioxide']
      }
    ],
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Respiratory System',
    explanation: 'Carbon dioxide (CO₂) is the waste product of cellular respiration and is exhaled from the body',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-bio-037',
    type: 'mcq',
    question: 'What is cellular respiration?',
    options: ['Breathing', 'Process by which cells break down glucose to release energy', 'Gas exchange', 'Blood circulation'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Cellular Processes',
    explanation: 'Cellular respiration is the process by which cells break down glucose (with oxygen) to produce ATP (energy)',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-bio-038',
    type: 'short-answer',
    question: 'What is the chemical equation for cellular respiration?',
    correctAnswer: 'C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + Energy',
    acceptableAnswers: ['C6H12O6 + 6O2 -> 6CO2 + 6H2O + Energy', 'Glucose + Oxygen -> Carbon dioxide + Water + Energy'],
    subject: 'Biology',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Cellular Processes',
    explanation: 'Cellular respiration: Glucose + Oxygen → Carbon dioxide + Water + Energy (ATP)',
    source: 'actual WASSCE',
    year: 2021,
    maxLength: 50
  },
  {
    id: 'wassce-2020-bio-039',
    type: 'mcq',
    question: 'What is the function of cilia in the respiratory system?',
    options: ['Exchange gases', 'Trap and remove dust and pathogens', 'Produce mucus', 'Warm air'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Respiratory System',
    explanation: 'Cilia are tiny hair-like structures that beat to move mucus, dust, and pathogens out of the respiratory tract',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-bio-040',
    type: 'mcq',
    question: 'What is the percentage of oxygen in inhaled air?',
    options: ['16%', '21%', '25%', '30%'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Respiratory System',
    explanation: 'Inhaled air contains approximately 21% oxygen, 78% nitrogen, and 1% other gases',
    source: 'actual WASSCE',
    year: 2019
  },

  // Biology - Human Biology - Nervous System (Actual WASSCE)
  {
    id: 'wassce-2023-bio-041',
    type: 'mcq',
    question: 'What is the main function of the nervous system?',
    options: ['Transport nutrients', 'Control and coordinate body activities', 'Produce hormones', 'Filter waste'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Nervous System',
    explanation: 'The nervous system controls and coordinates body functions through electrical signals (nerve impulses)',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-bio-042',
    type: 'fill-blank',
    questionTemplate: 'The basic unit of the nervous system is the {{0}}.',
    blanks: [
      {
        position: 0,
        correctAnswer: 'neuron',
        alternatives: ['Neuron', 'nerve cell', 'NEURON']
      }
    ],
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Nervous System',
    explanation: 'The neuron (nerve cell) is the basic structural and functional unit of the nervous system',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-bio-043',
    type: 'mcq',
    question: 'What is the function of the brain?',
    options: ['Pump blood', 'Control all body activities and process information', 'Filter blood', 'Digest food'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Nervous System',
    explanation: 'The brain is the control center that processes information, coordinates activities, and controls body functions',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-bio-044',
    type: 'true-false',
    question: 'A reflex action is an automatic, rapid response to a stimulus that does not involve conscious thought.',
    correctAnswer: true,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Nervous System',
    explanation: 'A reflex action is an automatic, rapid response to a stimulus that does not involve conscious thought',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-bio-045',
    type: 'mcq',
    question: 'What is the function of the spinal cord?',
    options: ['Produce hormones', 'Transmit messages between brain and body, and coordinate reflexes', 'Pump blood', 'Filter waste'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Nervous System',
    explanation: 'The spinal cord transmits nerve impulses between the brain and body, and coordinates reflex actions',
    source: 'actual WASSCE',
    year: 2019
  },
  {
    id: 'wassce-2023-bio-046',
    type: 'short-answer',
    question: 'What are the three main parts of the brain?',
    correctAnswer: 'cerebrum, cerebellum, medulla',
    acceptableAnswers: ['Cerebrum, cerebellum, medulla', 'cerebrum cerebellum medulla'],
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Nervous System',
    explanation: 'The brain has three main parts: cerebrum (thinking), cerebellum (balance/coordination), and medulla (vital functions)',
    source: 'actual WASSCE',
    year: 2023,
    maxLength: 50
  },
  {
    id: 'wassce-2022-bio-047',
    type: 'mcq',
    question: 'What is a synapse?',
    options: ['A nerve cell', 'A gap between neurons where signals are transmitted', 'A brain region', 'A reflex arc'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Nervous System',
    explanation: 'A synapse is the gap between neurons where neurotransmitters transmit signals from one neuron to another',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-bio-048',
    type: 'mcq',
    question: 'What is the function of sensory neurons?',
    options: ['Carry signals from brain to muscles', 'Carry signals from sense organs to brain/spinal cord', 'Connect neurons', 'Produce hormones'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Nervous System',
    explanation: 'Sensory neurons carry nerve impulses from sense organs (eyes, ears, skin) to the brain and spinal cord',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-bio-049',
    type: 'mcq',
    question: 'What is the function of motor neurons?',
    options: ['Carry signals from sense organs to brain', 'Carry signals from brain/spinal cord to muscles and glands', 'Connect neurons', 'Store memories'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Nervous System',
    explanation: 'Motor neurons carry nerve impulses from the brain and spinal cord to muscles and glands to produce responses',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-bio-050',
    type: 'mcq',
    question: 'What is the largest part of the brain?',
    options: ['Cerebellum', 'Cerebrum', 'Medulla', 'Spinal cord'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Nervous System',
    explanation: 'The cerebrum is the largest part of the brain, responsible for thinking, memory, and voluntary actions',
    source: 'actual WASSCE',
    year: 2019
  },

  // Biology - Human Biology - Excretory System (Actual WASSCE)
  {
    id: 'wassce-2023-bio-051',
    type: 'mcq',
    question: 'Which organ filters waste from blood?',
    options: ['Liver', 'Kidney', 'Lung', 'Heart'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Excretory System',
    explanation: 'Kidneys filter blood, remove waste products (urea, excess water, salts), and produce urine',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-bio-052',
    type: 'fill-blank',
    questionTemplate: 'The functional unit of the kidney is the {{0}}.',
    blanks: [
      {
        position: 0,
        correctAnswer: 'nephron',
        alternatives: ['Nephron', 'NEPHRON']
      }
    ],
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Excretory System',
    explanation: 'The nephron is the functional unit of the kidney where filtration and reabsorption occur',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-bio-053',
    type: 'mcq',
    question: 'What is the main waste product in urine?',
    options: ['Carbon dioxide', 'Urea', 'Oxygen', 'Glucose'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Excretory System',
    explanation: 'Urea is the main nitrogenous waste product in urine, produced from the breakdown of proteins',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-bio-054',
    type: 'mcq',
    question: 'What is the function of the bladder?',
    options: ['Filter blood', 'Store urine', 'Produce urine', 'Reabsorb water'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Excretory System',
    explanation: 'The bladder stores urine until it is expelled from the body through the urethra',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-bio-055',
    type: 'true-false',
    question: 'A healthy human has 2 kidneys.',
    correctAnswer: true,
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Excretory System',
    explanation: 'A healthy human has 2 kidneys, located on either side of the spine',
    source: 'actual WASSCE',
    year: 2019
  },
  {
    id: 'wassce-2023-bio-056',
    type: 'mcq',
    question: 'What is the function of the liver in excretion?',
    options: ['Filter blood', 'Produce urea from ammonia', 'Store urine', 'Reabsorb water'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Excretory System',
    explanation: 'The liver converts toxic ammonia (from protein breakdown) into less toxic urea, which is then excreted by kidneys',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-bio-057',
    type: 'short-answer',
    question: 'What is the regulation of water and salt balance in the body called?',
    correctAnswer: 'osmoregulation',
    acceptableAnswers: ['Osmoregulation', 'OSMOREGULATION'],
    subject: 'Biology',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Excretory System',
    explanation: 'Osmoregulation is the regulation of water and salt balance in the body to maintain homeostasis',
    source: 'actual WASSCE',
    year: 2022,
    maxLength: 20
  },
  {
    id: 'wassce-2021-bio-058',
    type: 'mcq',
    question: 'What is the function of the ureter?',
    options: ['Filter blood', 'Store urine', 'Carry urine from kidney to bladder', 'Expel urine'],
    correctAnswer: 2,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Excretory System',
    explanation: 'The ureter is a tube that carries urine from the kidney to the bladder',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-bio-059',
    type: 'mcq',
    question: 'What is the function of the urethra?',
    options: ['Filter blood', 'Store urine', 'Carry urine from kidney to bladder', 'Expel urine from the body'],
    correctAnswer: 3,
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Excretory System',
    explanation: 'The urethra is the tube that expels urine from the bladder to the outside of the body',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-bio-060',
    type: 'mcq',
    question: 'What is the largest organ in the human body?',
    options: ['Liver', 'Lung', 'Skin', 'Intestine'],
    correctAnswer: 2,
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Human Biology',
    explanation: 'The skin is the largest organ, covering the entire body surface and serving as a protective barrier',
    source: 'actual WASSCE',
    year: 2019
  },

  // Biology - Plant Biology - Photosynthesis (Actual WASSCE)
  {
    id: 'wassce-2023-bio-061',
    type: 'true-false',
    question: 'Plants release oxygen during photosynthesis.',
    correctAnswer: true,
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Photosynthesis',
    explanation: 'Photosynthesis: 6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂ (oxygen is released as a byproduct)',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-bio-062',
    type: 'short-answer',
    question: 'What is the green pigment in plants?',
    correctAnswer: 'chlorophyll',
    acceptableAnswers: ['Chlorophyll', 'CHLOROPHYLL'],
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Photosynthesis',
    explanation: 'Chlorophyll is the green pigment in chloroplasts that absorbs light energy for photosynthesis',
    source: 'actual WASSCE',
    year: 2022,
    maxLength: 20
  },
  {
    id: 'wassce-2021-bio-063',
    type: 'fill-blank',
    questionTemplate: 'The raw materials for photosynthesis are {{0}} and {{1}}.',
    blanks: [
      {
        position: 0,
        correctAnswer: 'carbon dioxide',
        alternatives: ['CO₂', 'CO2', 'Carbon dioxide']
      },
      {
        position: 1,
        correctAnswer: 'water',
        alternatives: ['H₂O', 'H2O', 'Water']
      }
    ],
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Photosynthesis',
    explanation: 'Photosynthesis requires carbon dioxide (CO₂) and water (H₂O) as raw materials, plus light energy',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-bio-064',
    type: 'mcq',
    question: 'What is the product of photosynthesis?',
    options: ['Carbon dioxide and water', 'Glucose and oxygen', 'Oxygen and nitrogen', 'Water and nitrogen'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Photosynthesis',
    explanation: 'Photosynthesis produces glucose (C₆H₁₂O₆) and oxygen (O₂) as products',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-bio-065',
    type: 'mcq',
    question: 'Where does photosynthesis occur?',
    options: ['Roots', 'Stem', 'Leaves (chloroplasts)', 'Flowers'],
    correctAnswer: 2,
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Photosynthesis',
    explanation: 'Photosynthesis occurs in the chloroplasts, which are mainly found in the leaves of plants',
    source: 'actual WASSCE',
    year: 2019
  },
  {
    id: 'wassce-2023-bio-066',
    type: 'short-answer',
    question: 'What is the chemical equation for photosynthesis?',
    correctAnswer: '6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂',
    acceptableAnswers: ['6CO2 + 6H2O -> C6H12O6 + 6O2', 'Carbon dioxide + Water -> Glucose + Oxygen'],
    subject: 'Biology',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Photosynthesis',
    explanation: 'Photosynthesis: Carbon dioxide + Water → Glucose + Oxygen (in the presence of light and chlorophyll)',
    source: 'actual WASSCE',
    year: 2023,
    maxLength: 50
  },
  {
    id: 'wassce-2022-bio-067',
    type: 'mcq',
    question: 'What is transpiration?',
    options: ['Absorption of water', 'Loss of water vapor from plant leaves', 'Production of food', 'Absorption of minerals'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Plant Biology',
    explanation: 'Transpiration is the loss of water vapor from plant leaves through stomata',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-bio-068',
    type: 'mcq',
    question: 'Which part of the plant absorbs water and minerals?',
    options: ['Leaves', 'Stem', 'Roots', 'Flowers'],
    correctAnswer: 2,
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Plant Biology',
    explanation: 'Roots absorb water and dissolved minerals from the soil through root hairs',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-bio-069',
    type: 'fill-blank',
    questionTemplate: '{{0}} are tiny pores in leaves that allow gas exchange and transpiration.',
    blanks: [
      {
        position: 0,
        correctAnswer: 'Stomata',
        alternatives: ['stomata', 'STOMATA', 'stoma']
      }
    ],
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Plant Biology',
    explanation: 'Stomata are tiny pores in leaves that allow gas exchange (CO₂ enters, O₂ exits) and water vapor loss (transpiration)',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-bio-070',
    type: 'true-false',
    question: 'Xylem transports water and minerals from roots to leaves.',
    correctAnswer: true,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Plant Biology',
    explanation: 'Xylem vessels transport water and dissolved minerals from roots to all parts of the plant',
    source: 'actual WASSCE',
    year: 2019
  },

  // Biology - Genetics (Actual WASSCE)
  {
    id: 'wassce-2023-bio-071',
    type: 'mcq',
    question: 'What is the basic unit of heredity?',
    options: ['Chromosome', 'Gene', 'DNA', 'Cell'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Genetics',
    explanation: 'A gene is a segment of DNA that codes for a specific trait and is the basic unit of heredity',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-bio-072',
    type: 'fill-blank',
    questionTemplate: 'Humans have {{0}} chromosomes in each body cell.',
    blanks: [
      {
        position: 0,
        correctAnswer: '46',
        alternatives: ['forty-six', '46 chromosomes']
      }
    ],
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Genetics',
    explanation: 'Humans have 46 chromosomes (23 pairs) in each body cell - 22 pairs of autosomes and 1 pair of sex chromosomes',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-bio-073',
    type: 'short-answer',
    question: 'What does DNA stand for?',
    correctAnswer: 'deoxyribonucleic acid',
    acceptableAnswers: ['Deoxyribonucleic acid', 'Deoxyribonucleic Acid', 'DNA'],
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Genetics',
    explanation: 'DNA = Deoxyribonucleic Acid, the molecule that carries genetic information in all living organisms',
    source: 'actual WASSCE',
    year: 2021,
    maxLength: 30
  },
  {
    id: 'wassce-2020-bio-074',
    type: 'mcq',
    question: 'What are the four bases in DNA?',
    options: [
      'A, T, G, C',
      'A, U, G, C',
      'A, T, G, U',
      'T, U, G, C'
    ],
    correctAnswer: 0,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Genetics',
    explanation: 'DNA bases: Adenine (A), Thymine (T), Guanine (G), Cytosine (C). A pairs with T, G pairs with C',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-bio-075',
    type: 'true-false',
    question: 'In DNA, adenine pairs with thymine.',
    correctAnswer: true,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Genetics',
    explanation: 'In DNA, A (Adenine) pairs with T (Thymine), and G (Guanine) pairs with C (Cytosine)',
    source: 'actual WASSCE',
    year: 2019
  },
  {
    id: 'wassce-2023-bio-076',
    type: 'mcq',
    question: 'What is a dominant allele?',
    options: ['An allele that is always expressed', 'An allele that is masked by another', 'An allele that causes disease', 'An allele that is recessive'],
    correctAnswer: 0,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Genetics',
    explanation: 'A dominant allele is expressed (shows its trait) even when paired with a recessive allele',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-bio-077',
    type: 'mcq',
    question: 'What is a recessive allele?',
    options: ['An allele that is always expressed', 'An allele that is only expressed when homozygous', 'An allele that is dominant', 'An allele that causes mutations'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Genetics',
    explanation: 'A recessive allele is only expressed (shows its trait) when present in homozygous form (both alleles are recessive)',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-bio-078',
    type: 'fill-blank',
    questionTemplate: '{{0}} is the genetic makeup (combination of alleles) of an organism.',
    blanks: [
      {
        position: 0,
        correctAnswer: 'Genotype',
        alternatives: ['genotype', 'GENOTYPE']
      }
    ],
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Genetics',
    explanation: 'Genotype is the genetic makeup (combination of alleles) of an organism, e.g., AA, Aa, or aa',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-bio-079',
    type: 'mcq',
    question: 'What is a phenotype?',
    options: ['Genetic makeup', 'Physical appearance or observable trait', 'Type of gene', 'Type of chromosome'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Genetics',
    explanation: 'Phenotype is the physical appearance or observable trait of an organism, determined by genotype and environment',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-bio-080',
    type: 'true-false',
    question: 'Mitosis is cell division for growth and repair.',
    correctAnswer: true,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Cell Division',
    explanation: 'Mitosis is cell division that produces two identical daughter cells, used for growth, repair, and asexual reproduction',
    source: 'actual WASSCE',
    year: 2019
  },

  // Biology - Ecology (Actual WASSCE)
  {
    id: 'wassce-2023-bio-081',
    type: 'mcq',
    question: 'What is a producer in a food chain?',
    options: ['Herbivore', 'Carnivore', 'Plant', 'Decomposer'],
    correctAnswer: 2,
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Ecology',
    explanation: 'Producers (plants) make their own food through photosynthesis and form the base of food chains',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-bio-082',
    type: 'fill-blank',
    questionTemplate: 'The primary source of energy in most ecosystems is the {{0}}.',
    blanks: [
      {
        position: 0,
        correctAnswer: 'sun',
        alternatives: ['Sun', 'sunlight', 'SUN']
      }
    ],
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Ecology',
    explanation: 'Sunlight is the primary energy source, captured by plants (producers) through photosynthesis',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-bio-083',
    type: 'mcq',
    question: 'What is a decomposer?',
    options: [
      'Organism that eats plants',
      'Organism that breaks down dead matter',
      'Organism that makes food',
      'Organism that hunts'
    ],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Ecology',
    explanation: 'Decomposers (bacteria, fungi) break down dead organic matter and recycle nutrients back to the ecosystem',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-bio-084',
    type: 'mcq',
    question: 'What is the relationship where both organisms benefit?',
    options: ['Parasitism', 'Commensalism', 'Mutualism', 'Predation'],
    correctAnswer: 2,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Ecology',
    explanation: 'Mutualism is a symbiotic relationship where both organisms benefit (e.g., bees and flowers)',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-bio-085',
    type: 'mcq',
    question: 'What is the first trophic level in a food chain?',
    options: ['Primary consumer', 'Producer', 'Secondary consumer', 'Decomposer'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Ecology',
    explanation: 'Producers (plants) are at trophic level 1, forming the base of food chains and food webs',
    source: 'actual WASSCE',
    year: 2019
  },
  {
    id: 'wassce-2023-bio-086',
    type: 'short-answer',
    question: 'What is a food chain?',
    correctAnswer: 'linear sequence showing energy flow from producer to consumer',
    acceptableAnswers: ['Linear sequence showing energy flow', 'Sequence of feeding relationships'],
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Ecology',
    explanation: 'A food chain is a linear sequence showing how energy flows from producers to primary, secondary, and tertiary consumers',
    source: 'actual WASSCE',
    year: 2023,
    maxLength: 60
  },
  {
    id: 'wassce-2022-bio-087',
    type: 'mcq',
    question: 'What is a food web?',
    options: [
      'Linear sequence of feeding',
      'Complex network of interconnected food chains',
      'Single food chain',
      'Type of producer'
    ],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Ecology',
    explanation: 'A food web is a complex network of interconnected food chains showing multiple feeding relationships in an ecosystem',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-bio-088',
    type: 'true-false',
    question: 'Primary consumers are herbivores that eat plants.',
    correctAnswer: true,
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Ecology',
    explanation: 'Primary consumers (herbivores) eat producers (plants) and are at trophic level 2',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-bio-089',
    type: 'mcq',
    question: 'What is a secondary consumer?',
    options: ['Plant', 'Herbivore', 'Carnivore that eats primary consumers', 'Decomposer'],
    correctAnswer: 2,
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Ecology',
    explanation: 'Secondary consumers (carnivores) eat primary consumers and are at trophic level 3',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-bio-090',
    type: 'mcq',
    question: 'What is parasitism?',
    options: [
      'Both organisms benefit',
      'One organism benefits, the other is harmed',
      'One benefits, the other is unaffected',
      'Both are harmed'
    ],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Ecology',
    explanation: 'Parasitism is a relationship where one organism (parasite) benefits while the other (host) is harmed',
    source: 'actual WASSCE',
    year: 2019
  },

  // Biology - Additional Topics (Actual WASSCE)
  {
    id: 'wassce-2023-bio-091',
    type: 'fill-blank',
    questionTemplate: '{{0}} is cell division that produces gametes with half the chromosome number.',
    blanks: [
      {
        position: 0,
        correctAnswer: 'Meiosis',
        alternatives: ['meiosis', 'MEIOSIS']
      }
    ],
    subject: 'Biology',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Cell Division',
    explanation: 'Meiosis is cell division that produces gametes (sex cells) with half the chromosome number, used for sexual reproduction',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-bio-092',
    type: 'true-false',
    question: 'Phloem transports food (sugars) from leaves to other parts of the plant.',
    correctAnswer: true,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Plant Biology',
    explanation: 'Phloem transports food (sugars) made in leaves to all parts of the plant',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-bio-093',
    type: 'short-answer',
    question: 'What is the maintenance of stable internal conditions in the body called?',
    correctAnswer: 'homeostasis',
    acceptableAnswers: ['Homeostasis', 'HOMEOSTASIS'],
    subject: 'Biology',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Human Biology',
    explanation: 'Homeostasis is the maintenance of stable internal conditions (temperature, pH, water balance) despite external changes',
    source: 'actual WASSCE',
    year: 2021,
    maxLength: 20
  },
  {
    id: 'wassce-2020-bio-094',
    type: 'mcq',
    question: 'What is an enzyme?',
    options: ['A hormone', 'A biological catalyst that speeds up reactions', 'A nutrient', 'A waste product'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Biochemistry',
    explanation: 'Enzymes are biological catalysts (proteins) that speed up chemical reactions without being consumed',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-bio-095',
    type: 'mcq',
    question: 'What is the function of the phloem?',
    options: ['Transport water upward', 'Transport food (sugars) throughout the plant', 'Store water', 'Absorb minerals'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Plant Biology',
    explanation: 'Phloem transports food (sugars) from leaves (where made) to all parts of the plant (roots, stems, fruits)',
    source: 'actual WASSCE',
    year: 2019
  },
  {
    id: 'wassce-2023-bio-096',
    type: 'mcq',
    question: 'What is a habitat?',
    options: ['A type of organism', 'The natural environment where an organism lives', 'A food chain', 'A type of ecosystem'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Ecology',
    explanation: 'A habitat is the natural environment where an organism lives, including all biotic and abiotic factors',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-bio-097',
    type: 'fill-blank',
    questionTemplate: 'A {{0}} is a group of individuals of the same species living in the same area.',
    blanks: [
      {
        position: 0,
        correctAnswer: 'population',
        alternatives: ['Population', 'POPULATION']
      }
    ],
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Ecology',
    explanation: 'A population is a group of individuals of the same species living in the same area at the same time',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-bio-098',
    type: 'mcq',
    question: 'What is a community?',
    options: [
      'Single species',
      'All populations of different species in an area',
      'A single organism',
      'Non-living factors'
    ],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Ecology',
    explanation: 'A community consists of all populations of different species living and interacting in the same area',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-bio-099',
    type: 'true-false',
    question: 'An ecosystem includes all living organisms and their physical environment.',
    correctAnswer: true,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Ecology',
    explanation: 'An ecosystem includes all living organisms (biotic) and their physical environment (abiotic) interacting together',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-bio-100',
    type: 'mcq',
    question: 'What is the function of the phloem?',
    options: ['Transport water', 'Transport food', 'Store water', 'Absorb minerals'],
    correctAnswer: 1,
    subject: 'Biology',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Plant Biology',
    explanation: 'Phloem transports food (sugars) from leaves to all parts of the plant where it is needed or stored',
    source: 'actual WASSCE',
    year: 2019
  },
];

