// English Language Questions for SHS
// Initial batch of questions migrated to modular ChallengeQuestion format
// NOTE: These are practice-style WASSCE-level questions, not yet tagged as verified past questions.

import type { ChallengeQuestion } from '../types';

export const englishLanguageQuestions: ChallengeQuestion[] = [
  // ============================================
  // MCQ Questions (Initial Batch)
  // ============================================

  // English Language - Grammar (Tenses & Agreement)
  {
    id: 'shs-eng-001',
    type: 'mcq',
    question: 'Choose the correct option to complete the sentence: "She _____ to school every day."',
    options: ['go', 'goes', 'going', 'gone'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Present Simple Tense',
    explanation: 'In the simple present tense, we add -es for third person singular: She goes.',
    source: 'practice',
  },
  {
    id: 'shs-eng-002',
    type: 'mcq',
    question: 'Choose the correctly punctuated sentence.',
    options: [
      'its raining heavily outside.',
      "It's raining heavily outside.",
      "Its' raining heavily outside.",
      'Its raining heavily outside.',
    ],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Apostrophes & Contractions',
    explanation: 'The correct contraction of \"it is\" is \"it\'s\" with an apostrophe before s.',
    source: 'practice',
  },

  // English Language - Vocabulary & Word Choice
  {
    id: 'shs-eng-003',
    type: 'mcq',
    question: 'Which word best completes the sentence: "He is very _____; he never wastes money."',
    options: ['generous', 'thrifty', 'careless', 'wasteful'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Vocabulary',
    explanation: '“Thrifty” means careful with money and not wasteful.',
    source: 'practice',
  },
  {
    id: 'shs-eng-004',
    type: 'mcq',
    question: 'Choose the word that is opposite in meaning to "scarce".',
    options: ['few', 'rare', 'plentiful', 'little'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Antonyms',
    explanation: 'The opposite of “scarce” is “plentiful”.',
    source: 'practice',
  },

  // English Language - Sentence Structure & Clauses
  {
    id: 'shs-eng-005',
    type: 'mcq',
    question: 'Which of the following is a complex sentence?',
    options: [
      'He came, he saw, he conquered.',
      'She went home and slept.',
      'Although it was raining, we went to school.',
      'The boy ran quickly.',
    ],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Sentence Types',
    explanation: 'A complex sentence has one main clause and at least one subordinate clause, e.g. “Although it was raining, we went to school.”',
    source: 'practice',
  },
  {
    id: 'shs-eng-006',
    type: 'mcq',
    question: 'Identify the subordinate clause in the sentence: "I will call you when I arrive."',
    options: ['I will call you', 'when I arrive', 'I will', 'call you'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Clauses',
    explanation: '“when I arrive” is the subordinate (dependent) clause; it cannot stand alone.',
    source: 'practice',
  },

  // English Language - Comprehension Skills (short item-based)
  {
    id: 'shs-eng-007',
    type: 'mcq',
    question: 'In comprehension, the main idea of a paragraph is usually found in the:',
    options: ['first or last sentence', 'middle sentence only', 'shortest sentence', 'longest sentence'],
    correctAnswer: 0,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Comprehension',
    explanation: 'Writers often place the main idea in the first or last sentence of a paragraph.',
    source: 'practice',
  },
  {
    id: 'shs-eng-008',
    type: 'mcq',
    question: 'A passage that tells a story is mainly:',
    options: ['descriptive', 'expository', 'narrative', 'argumentative'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Comprehension / Genres',
    explanation: 'A story-telling passage is narrative.',
    source: 'practice',
  },

  // English Language - Idioms & Figures of Speech
  {
    id: 'shs-eng-009',
    type: 'mcq',
    question: 'The expression "break the ice" means:',
    options: [
      'to smash something',
      'to make people feel more relaxed in a new situation',
      'to cause trouble',
      'to end a relationship',
    ],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Idioms',
    explanation: '“Break the ice” means to make people feel more comfortable or start a friendly conversation.',
    source: 'practice',
  },
  {
    id: 'shs-eng-010',
    type: 'mcq',
    question: 'Which figure of speech is used in the sentence: "The stars danced in the sky"?',
    options: ['Simile', 'Metaphor', 'Personification', 'Hyperbole'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Figures of Speech',
    explanation: 'Giving human action “danced” to non-human “stars” is personification.',
    source: 'practice',
  },

  // Batch 1 - First 25 additional questions (011-035)
  {
    id: 'shs-eng-011',
    type: 'mcq',
    question: 'Choose the correct form: "Neither the students nor the teacher _____ present."',
    options: ['was', 'were', 'are', 'is'],
    correctAnswer: 0,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Subject-Verb Agreement',
    explanation: 'With "neither...nor", the verb agrees with the subject closer to it. "Teacher" is singular, so use "was".',
    source: 'practice',
  },
  {
    id: 'shs-eng-012',
    type: 'mcq',
    question: 'Which sentence uses the correct past tense?',
    options: [
      'She has went to the market yesterday.',
      'She went to the market yesterday.',
      'She had went to the market yesterday.',
      'She have went to the market yesterday.',
    ],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Past Simple Tense',
    explanation: 'For actions completed in the past at a specific time, use past simple: "went" (not "has went").',
    source: 'practice',
  },
  {
    id: 'shs-eng-013',
    type: 'mcq',
    question: 'Choose the correct comparative form: "This book is _____ than the other one."',
    options: ['good', 'better', 'best', 'more good'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Comparatives',
    explanation: 'The comparative form of "good" is "better" (not "more good").',
    source: 'practice',
  },
  {
    id: 'shs-eng-014',
    type: 'mcq',
    question: 'Which word is a synonym for "huge"?',
    options: ['tiny', 'enormous', 'small', 'minute'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Synonyms',
    explanation: '"Enormous" means very large, making it a synonym for "huge".',
    source: 'practice',
  },
  {
    id: 'shs-eng-015',
    type: 'mcq',
    question: 'Identify the error: "The team of players are ready."',
    options: ['team', 'players', 'are', 'ready'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Subject-Verb Agreement',
    explanation: '"Team" is a collective noun treated as singular, so it should be "is ready" (not "are ready").',
    source: 'practice',
  },
  {
    id: 'shs-eng-016',
    type: 'mcq',
    question: 'Choose the correct preposition: "She is good _____ mathematics."',
    options: ['at', 'in', 'on', 'for'],
    correctAnswer: 0,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Prepositions',
    explanation: 'We use "good at" to express proficiency in a subject or activity.',
    source: 'practice',
  },
  {
    id: 'shs-eng-017',
    type: 'mcq',
    question: 'Which sentence is in the passive voice?',
    options: [
      'The teacher gave the students homework.',
      'The students received homework from the teacher.',
      'Homework was given to the students by the teacher.',
      'The teacher gives homework to the students.',
    ],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Active and Passive Voice',
    explanation: 'In passive voice, the object becomes the subject: "Homework was given..." (not "The teacher gave...").',
    source: 'practice',
  },
  {
    id: 'shs-eng-018',
    type: 'mcq',
    question: 'Choose the correct modal verb: "You _____ study hard to pass the exam."',
    options: ['can', 'must', 'might', 'could'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Modal Verbs',
    explanation: '"Must" expresses necessity or strong obligation, appropriate here.',
    source: 'practice',
  },
  {
    id: 'shs-eng-019',
    type: 'mcq',
    question: 'Which sentence contains a relative clause?',
    options: [
      'The book is on the table.',
      'The book that I bought is interesting.',
      'I bought a book yesterday.',
      'Books are interesting.',
    ],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Relative Clauses',
    explanation: '"That I bought" is a relative clause modifying "book".',
    source: 'practice',
  },
  {
    id: 'shs-eng-020',
    type: 'mcq',
    question: 'What is the plural form of "child"?',
    options: ['childs', 'children', 'childes', 'childrens'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Plurals',
    explanation: '"Children" is the irregular plural form of "child".',
    source: 'practice',
  },
  {
    id: 'shs-eng-021',
    type: 'mcq',
    question: 'Choose the correct form: "The number of students _____ increased."',
    options: ['has', 'have', 'are', 'were'],
    correctAnswer: 0,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Subject-Verb Agreement',
    explanation: '"The number of" is singular, so use "has" (not "have").',
    source: 'practice',
  },
  {
    id: 'shs-eng-022',
    type: 'mcq',
    question: 'Which sentence uses the conditional correctly?',
    options: [
      'If I was rich, I would travel.',
      'If I were rich, I would travel.',
      'If I am rich, I would travel.',
      'If I will be rich, I would travel.',
    ],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Conditionals',
    explanation: 'In the second conditional (hypothetical), use "were" (not "was") for all subjects: "If I were..."',
    source: 'practice',
  },
  {
    id: 'shs-eng-023',
    type: 'mcq',
    question: 'Identify the type of error: "He don\'t like apples."',
    options: ['Spelling error', 'Grammar error', 'Punctuation error', 'Capitalization error'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Grammar',
    explanation: 'With third person singular "he", use "doesn\'t" (not "don\'t"). This is a grammar error.',
    source: 'practice',
  },
  {
    id: 'shs-eng-024',
    type: 'mcq',
    question: 'Which word is NOT a conjunction?',
    options: ['and', 'but', 'because', 'quickly'],
    correctAnswer: 3,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Parts of Speech',
    explanation: '"Quickly" is an adverb, not a conjunction. "And", "but", and "because" are conjunctions.',
    source: 'practice',
  },
  {
    id: 'shs-eng-025',
    type: 'mcq',
    question: 'Choose the correct article: "_____ apple a day keeps the doctor away."',
    options: ['A', 'An', 'The', 'No article'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Articles',
    explanation: 'Use "An" before words starting with a vowel sound: "An apple".',
    source: 'practice',
  },
  {
    id: 'shs-eng-026',
    type: 'mcq',
    question: 'Which sentence uses the present perfect tense correctly?',
    options: [
      'I have seen that movie yesterday.',
      'I saw that movie yesterday.',
      'I have seen that movie before.',
      'I see that movie yesterday.',
    ],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Present Perfect Tense',
    explanation: 'Present perfect is used for past actions with present relevance, not with specific past times like "yesterday".',
    source: 'practice',
  },
  {
    id: 'shs-eng-027',
    type: 'mcq',
    question: 'What does the idiom "call it a day" mean?',
    options: ['Start working', 'Stop working for the day', 'Make a phone call', 'Plan for tomorrow'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Idioms',
    explanation: '"Call it a day" means to stop working or to finish what you\'re doing for that day.',
    source: 'practice',
  },
  {
    id: 'shs-eng-028',
    type: 'mcq',
    question: 'Which sentence is a compound sentence?',
    options: [
      'She likes reading.',
      'She likes reading, and he likes writing.',
      'Because she likes reading, she buys many books.',
      'Reading is enjoyable.',
    ],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Sentence Types',
    explanation: 'A compound sentence has two or more independent clauses joined by a conjunction like "and".',
    source: 'practice',
  },
  {
    id: 'shs-eng-029',
    type: 'mcq',
    question: 'Choose the correct word: "The _____ of the storm was devastating."',
    options: ['affect', 'effect', 'affects', 'effects'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Commonly Confused Words',
    explanation: '"Effect" (noun) means result. "Affect" (verb) means to influence.',
    source: 'practice',
  },
  {
    id: 'shs-eng-030',
    type: 'mcq',
    question: 'Which sentence has correct punctuation?',
    options: [
      'I went to the market, I bought fruits.',
      'I went to the market; I bought fruits.',
      'I went to the market I bought fruits.',
      'I went to the market, and I bought fruits.',
    ],
    correctAnswer: 3,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Punctuation',
    explanation: 'Two independent clauses need a comma with a conjunction (and) or a semicolon. Option 3 uses a comma with "and".',
    source: 'practice',
  },
  {
    id: 'shs-eng-031',
    type: 'mcq',
    question: 'What is the past participle of "break"?',
    options: ['break', 'broke', 'broken', 'breaked'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Irregular Verbs',
    explanation: 'The past participle of "break" is "broken" (break - broke - broken).',
    source: 'practice',
  },
  {
    id: 'shs-eng-032',
    type: 'mcq',
    question: 'Which sentence uses reported speech correctly?',
    options: [
      'She said, "I am tired."',
      'She said that she was tired.',
      'She said that she is tired.',
      'She said, "I was tired."',
    ],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Reported Speech',
    explanation: 'In reported speech, present tense changes to past tense: "am" becomes "was".',
    source: 'practice',
  },
  {
    id: 'shs-eng-033',
    type: 'mcq',
    question: 'Choose the correct form: "Each of the students _____ a book."',
    options: ['have', 'has', 'are', 'were'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Subject-Verb Agreement',
    explanation: '"Each" is singular, so use "has" (not "have").',
    source: 'practice',
  },
  {
    id: 'shs-eng-034',
    type: 'mcq',
    question: 'Which figure of speech is used: "Time is money"?',
    options: ['Simile', 'Metaphor', 'Personification', 'Hyperbole'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Figures of Speech',
    explanation: 'A metaphor directly compares two things without "like" or "as": time is directly compared to money.',
    source: 'practice',
  },
  {
    id: 'shs-eng-035',
    type: 'mcq',
    question: 'Which sentence is grammatically correct?',
    options: [
      'Between you and I, this is wrong.',
      'Between you and me, this is wrong.',
      'Between you and myself, this is wrong.',
      'Between you and we, this is wrong.',
    ],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Pronouns',
    explanation: 'After a preposition like "between", use object pronouns: "me" (not "I").',
    source: 'practice',
  },
];


