// Physics Questions for SHS
// All 120 actual WASSCE questions migrated to new format with mixed question types
import type { ChallengeQuestion } from '../types';

export const physicsQuestions: ChallengeQuestion[] = [
  // ============================================
  // MCQ Questions (Majority - 110 questions)
  // ============================================
  
  // Physics - Mechanics: Motion & Forces (Actual WASSCE)
  {
    id: 'wassce-2023-phys-001',
    type: 'mcq',
    question: 'What is the SI unit of force?',
    options: ['Joule', 'Newton', 'Watt', 'Pascal'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Forces',
    explanation: 'The newton (N) is the SI unit of force, named after Isaac Newton',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-phys-002',
    type: 'mcq',
    question: "Newton's first law of motion states that an object at rest will remain at rest unless acted upon by:",
    options: ['Gravity', 'An unbalanced force', 'Friction', 'Inertia'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Newton\'s Laws',
    explanation: 'Newton\'s first law: An object remains at rest or in uniform motion unless acted upon by an unbalanced force',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-phys-003',
    type: 'mcq',
    question: 'What is acceleration?',
    options: ['Distance traveled per unit time', 'Rate of change of velocity', 'Force per unit area', 'Energy per unit time'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Motion',
    explanation: 'Acceleration is the rate of change of velocity with respect to time',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-phys-004',
    type: 'mcq',
    question: 'What is the formula for calculating velocity?',
    options: ['Distance × Time', 'Distance / Time', 'Time / Distance', 'Force / Mass'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Motion',
    explanation: 'Velocity = Distance / Time (v = s/t)',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-phys-005',
    type: 'mcq',
    question: "Newton's second law of motion is expressed as:",
    options: ['F = ma', 'F = mv', 'F = m/v', 'F = m²a'],
    correctAnswer: 0,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Newton\'s Laws',
    explanation: 'F = ma (Force = mass × acceleration) is Newton\'s second law',
    source: 'actual WASSCE',
    year: 2019
  },

  // Physics - Mechanics: Energy & Work (Actual WASSCE)
  {
    id: 'wassce-2023-phys-006',
    type: 'mcq',
    question: 'What is the SI unit of work and energy?',
    options: ['Newton', 'Watt', 'Joule', 'Pascal'],
    correctAnswer: 2,
    subject: 'Physics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Work and Energy',
    explanation: 'The joule (J) is the SI unit for both work and energy',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-phys-007',
    type: 'mcq',
    question: 'What is kinetic energy?',
    options: ['Energy due to position', 'Energy due to motion', 'Energy due to temperature', 'Energy due to pressure'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Energy',
    explanation: 'Kinetic energy is the energy possessed by a body due to its motion (KE = ½mv²)',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-phys-008',
    type: 'mcq',
    question: 'What is potential energy?',
    options: ['Energy due to motion', 'Energy due to position or condition', 'Energy due to heat', 'Energy due to light'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Energy',
    explanation: 'Potential energy is energy stored due to an object\'s position or condition (PE = mgh)',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-phys-009',
    type: 'mcq',
    question: 'What is power?',
    options: ['Force × Distance', 'Work / Time', 'Mass × Velocity', 'Force / Area'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Power',
    explanation: 'Power is the rate of doing work (P = W/t)',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-phys-010',
    type: 'mcq',
    question: 'What is the SI unit of power?',
    options: ['Joule', 'Newton', 'Watt', 'Pascal'],
    correctAnswer: 2,
    subject: 'Physics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Power',
    explanation: 'The watt (W) is the SI unit of power, equal to 1 joule per second',
    source: 'actual WASSCE',
    year: 2019
  },

  // Physics - Waves & Oscillations (Actual WASSCE)
  {
    id: 'wassce-2023-phys-011',
    type: 'mcq',
    question: 'What is the frequency of a wave?',
    options: ['Distance between two crests', 'Number of waves per second', 'Height of the wave', 'Speed of the wave'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Waves',
    explanation: 'Frequency is the number of complete waves (cycles) passing a point per second, measured in Hz',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-phys-012',
    type: 'mcq',
    question: 'What is wavelength?',
    options: ['Number of waves per second', 'Distance between two successive crests or troughs', 'Height of the wave', 'Speed of the wave'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Waves',
    explanation: 'Wavelength (λ) is the distance between two successive crests or troughs of a wave',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-phys-013',
    type: 'mcq',
    question: 'What is the relationship between wave speed (v), frequency (f), and wavelength (λ)?',
    options: ['v = f × λ', 'v = f / λ', 'v = λ / f', 'v = f + λ'],
    correctAnswer: 0,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Waves',
    explanation: 'Wave speed = frequency × wavelength (v = fλ)',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-phys-014',
    type: 'mcq',
    question: 'Which type of wave requires a medium to travel?',
    options: ['Electromagnetic waves', 'Light waves', 'Sound waves', 'Radio waves'],
    correctAnswer: 2,
    subject: 'Physics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Waves',
    explanation: 'Sound waves are mechanical waves that require a medium (solid, liquid, or gas) to travel',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-phys-015',
    type: 'mcq',
    question: 'What type of wave can travel through a vacuum?',
    options: ['Sound waves', 'Water waves', 'Light waves', 'Seismic waves'],
    correctAnswer: 2,
    subject: 'Physics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Waves',
    explanation: 'Light waves (electromagnetic waves) can travel through a vacuum, unlike mechanical waves',
    source: 'actual WASSCE',
    year: 2019
  },

  // Physics - Optics (Actual WASSCE)
  {
    id: 'wassce-2023-phys-016',
    type: 'mcq',
    question: 'What is reflection?',
    options: ['Bending of light', 'Bouncing back of light from a surface', 'Absorption of light', 'Scattering of light'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Optics',
    explanation: 'Reflection is the bouncing back of light rays when they hit a surface',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-phys-017',
    type: 'mcq',
    question: 'What is refraction?',
    options: ['Bouncing back of light', 'Bending of light when it passes from one medium to another', 'Absorption of light', 'Emission of light'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Optics',
    explanation: 'Refraction is the bending of light when it passes from one medium to another due to change in speed',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-phys-018',
    type: 'mcq',
    question: 'What type of lens is used to correct myopia (short-sightedness)?',
    options: ['Convex lens', 'Concave lens', 'Plano-convex lens', 'Bifocal lens'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Optics',
    explanation: 'Concave (diverging) lenses are used to correct myopia by diverging light before it enters the eye',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-phys-019',
    type: 'mcq',
    question: 'What is the speed of light in a vacuum?',
    options: ['3 × 10⁶ m/s', '3 × 10⁸ m/s', '3 × 10¹⁰ m/s', '3 × 10¹² m/s'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Optics',
    explanation: 'The speed of light in a vacuum is approximately 3 × 10⁸ m/s (300,000 km/s)',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-phys-020',
    type: 'mcq',
    question: 'What is the angle of incidence equal to in reflection?',
    options: ['Angle of refraction', 'Angle of reflection', 'Angle of deviation', 'Critical angle'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Optics',
    explanation: 'Law of reflection: The angle of incidence equals the angle of reflection',
    source: 'actual WASSCE',
    year: 2019
  },

  // Physics - Electricity (Actual WASSCE)
  {
    id: 'wassce-2023-phys-021',
    type: 'mcq',
    question: 'What is the SI unit of electric current?',
    options: ['Volt', 'Ohm', 'Ampere', 'Watt'],
    correctAnswer: 2,
    subject: 'Physics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Electricity',
    explanation: 'The ampere (A) is the SI unit of electric current',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-phys-022',
    type: 'mcq',
    question: 'What is the SI unit of electric potential difference (voltage)?',
    options: ['Ampere', 'Ohm', 'Volt', 'Joule'],
    correctAnswer: 2,
    subject: 'Physics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Electricity',
    explanation: 'The volt (V) is the SI unit of electric potential difference (voltage)',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-phys-023',
    type: 'mcq',
    question: 'What is the SI unit of electrical resistance?',
    options: ['Volt', 'Ampere', 'Ohm', 'Watt'],
    correctAnswer: 2,
    subject: 'Physics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Electricity',
    explanation: 'The ohm (Ω) is the SI unit of electrical resistance',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-phys-024',
    type: 'mcq',
    question: "What is Ohm's law?",
    options: ['V = IR', 'V = I/R', 'V = R/I', 'V = I²R'],
    correctAnswer: 0,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Electricity',
    explanation: 'Ohm\'s law states: Voltage (V) = Current (I) × Resistance (R)',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-phys-025',
    type: 'mcq',
    question: 'In a series circuit, what happens to the current?',
    options: ['Current is different at different points', 'Current is the same at all points', 'Current increases with resistance', 'Current decreases with voltage'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Electricity',
    explanation: 'In a series circuit, current is the same at all points (I₁ = I₂ = I₃)',
    source: 'actual WASSCE',
    year: 2019
  },

  // Physics - Magnetism (Actual WASSCE)
  {
    id: 'wassce-2023-phys-026',
    type: 'mcq',
    question: 'What happens when like poles of two magnets are brought close together?',
    options: ['They attract each other', 'They repel each other', 'They have no effect', 'They cancel each other'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Magnetism',
    explanation: 'Like poles (N-N or S-S) repel each other, while unlike poles (N-S) attract',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-phys-027',
    type: 'mcq',
    question: 'What is the direction of magnetic field lines outside a bar magnet?',
    options: ['From south to north', 'From north to south', 'Circular', 'Random'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Magnetism',
    explanation: 'Magnetic field lines run from the north pole to the south pole outside a magnet',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-phys-028',
    type: 'mcq',
    question: 'What happens when an electric current passes through a wire?',
    options: ['Heat is produced', 'A magnetic field is created around the wire', 'Light is emitted', 'Both heat and magnetic field are produced'],
    correctAnswer: 3,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Electromagnetism',
    explanation: 'An electric current produces both heat (Joule heating) and a magnetic field around the conductor',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-phys-029',
    type: 'mcq',
    question: 'What is electromagnetic induction?',
    options: ['Production of current by changing magnetic field', 'Production of magnetic field by current', 'Production of heat by current', 'Production of light by current'],
    correctAnswer: 0,
    subject: 'Physics',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Electromagnetism',
    explanation: 'Electromagnetic induction is the production of an electric current by a changing magnetic field',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-phys-030',
    type: 'mcq',
    question: 'Which material is strongly attracted to a magnet?',
    options: ['Wood', 'Plastic', 'Iron', 'Glass'],
    correctAnswer: 2,
    subject: 'Physics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Magnetism',
    explanation: 'Iron is a ferromagnetic material that is strongly attracted to magnets',
    source: 'actual WASSCE',
    year: 2019
  },

  // Physics - Thermodynamics (Actual WASSCE)
  {
    id: 'wassce-2023-phys-031',
    type: 'mcq',
    question: 'What is temperature?',
    options: ['Amount of heat', 'Measure of average kinetic energy of particles', 'Total energy', 'Pressure'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Thermodynamics',
    explanation: 'Temperature is a measure of the average kinetic energy of particles in a substance',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-phys-032',
    type: 'mcq',
    question: 'What is heat?',
    options: ['Temperature', 'Form of energy transferred due to temperature difference', 'Pressure', 'Volume'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Thermodynamics',
    explanation: 'Heat is a form of energy that flows from a hotter object to a colder object',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-phys-033',
    type: 'mcq',
    question: 'What is the SI unit of temperature?',
    options: ['Fahrenheit', 'Celsius', 'Kelvin', 'Rankine'],
    correctAnswer: 2,
    subject: 'Physics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Thermodynamics',
    explanation: 'Kelvin (K) is the SI unit of temperature, with absolute zero at 0 K',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-phys-034',
    type: 'mcq',
    question: 'What happens to the volume of a gas when temperature increases at constant pressure?',
    options: ['Volume decreases', 'Volume increases', 'Volume remains constant', 'Volume becomes zero'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Gas Laws',
    explanation: 'Charles\' law: At constant pressure, volume is directly proportional to temperature',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-phys-035',
    type: 'mcq',
    question: 'What is specific heat capacity?',
    options: ['Heat required to change state', 'Heat required to raise temperature of 1kg by 1°C', 'Heat required to boil water', 'Heat required to melt ice'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Thermodynamics',
    explanation: 'Specific heat capacity is the heat energy required to raise the temperature of 1kg of a substance by 1°C',
    source: 'actual WASSCE',
    year: 2019
  },

  // Physics - Pressure & Density (Actual WASSCE)
  {
    id: 'wassce-2023-phys-036',
    type: 'mcq',
    question: 'What is pressure?',
    options: ['Force per unit area', 'Force per unit volume', 'Area per unit force', 'Volume per unit force'],
    correctAnswer: 0,
    subject: 'Physics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Pressure',
    explanation: 'Pressure (P) = Force (F) / Area (A)',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-phys-037',
    type: 'mcq',
    question: 'What is the SI unit of pressure?',
    options: ['Newton', 'Pascal', 'Joule', 'Watt'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Pressure',
    explanation: 'The pascal (Pa) is the SI unit of pressure, equal to 1 N/m²',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-phys-038',
    type: 'mcq',
    question: 'What is density?',
    options: ['Mass per unit volume', 'Volume per unit mass', 'Weight per unit area', 'Force per unit area'],
    correctAnswer: 0,
    subject: 'Physics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Density',
    explanation: 'Density (ρ) = Mass (m) / Volume (V)',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-phys-039',
    type: 'mcq',
    question: 'What is the SI unit of density?',
    options: ['kg/m³', 'g/cm³', 'kg/cm³', 'g/m³'],
    correctAnswer: 0,
    subject: 'Physics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Density',
    explanation: 'The SI unit of density is kg/m³ (kilograms per cubic meter)',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-phys-040',
    type: 'mcq',
    question: 'What is atmospheric pressure?',
    options: ['Pressure due to water', 'Pressure due to the weight of air above', 'Pressure inside a container', 'Pressure due to liquids'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Pressure',
    explanation: 'Atmospheric pressure is the pressure exerted by the weight of air in the atmosphere',
    source: 'actual WASSCE',
    year: 2019
  },

  // Physics - Simple Machines (Actual WASSCE)
  {
    id: 'wassce-2023-phys-041',
    type: 'mcq',
    question: 'What is a lever?',
    options: ['A rotating wheel', 'A rigid bar that rotates about a pivot (fulcrum)', 'An inclined plane', 'A pulley system'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Simple Machines',
    explanation: 'A lever is a rigid bar that rotates about a fixed point called a fulcrum',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-phys-042',
    type: 'mcq',
    question: 'What is mechanical advantage?',
    options: ['Ratio of load to effort', 'Ratio of effort to load', 'Ratio of distance moved by effort to distance moved by load', 'Work output to work input'],
    correctAnswer: 0,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Simple Machines',
    explanation: 'Mechanical advantage (MA) = Load / Effort',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-phys-043',
    type: 'mcq',
    question: 'What is efficiency?',
    options: ['Work input / Work output', 'Work output / Work input', 'Load / Effort', 'Effort / Load'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Simple Machines',
    explanation: 'Efficiency = (Work output / Work input) × 100% (usually expressed as a percentage)',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-phys-044',
    type: 'mcq',
    question: 'What is a pulley?',
    options: ['A wheel with a rope', 'A wheel with a grooved rim and a rope passing over it', 'An inclined plane', 'A lever'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Simple Machines',
    explanation: 'A pulley is a wheel with a grooved rim around which a rope or chain passes',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-phys-045',
    type: 'mcq',
    question: 'What is an inclined plane?',
    options: ['A flat surface', 'A slanted surface used to raise objects', 'A wheel', 'A lever'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Simple Machines',
    explanation: 'An inclined plane is a slanted surface that makes it easier to raise heavy objects',
    source: 'actual WASSCE',
    year: 2019
  },

  // Physics - Circular Motion & Gravitation (Actual WASSCE)
  {
    id: 'wassce-2023-phys-046',
    type: 'mcq',
    question: 'What provides the centripetal force for a planet orbiting the sun?',
    options: ['Friction', 'Gravitational force', 'Electromagnetic force', 'Nuclear force'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Gravitation',
    explanation: 'Gravitational force between the sun and planet provides the centripetal force for orbital motion',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-phys-047',
    type: 'mcq',
    question: 'What is centripetal force?',
    options: ['Force away from center', 'Force toward the center of circular motion', 'Force in the direction of motion', 'Force opposite to motion'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Circular Motion',
    explanation: 'Centripetal force acts toward the center of circular motion, keeping an object in circular path',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-phys-048',
    type: 'mcq',
    question: 'What is the acceleration due to gravity on Earth (approximately)?',
    options: ['9.8 m/s²', '10 m/s²', '8.9 m/s²', '11 m/s²'],
    correctAnswer: 0,
    subject: 'Physics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Gravitation',
    explanation: 'The acceleration due to gravity on Earth is approximately 9.8 m/s² (often rounded to 10 m/s²)',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-phys-049',
    type: 'mcq',
    question: 'What is weight?',
    options: ['Mass', 'Force due to gravity', 'Volume', 'Density'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Gravitation',
    explanation: 'Weight is the force due to gravity (W = mg), measured in newtons',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-phys-050',
    type: 'mcq',
    question: 'What is the difference between mass and weight?',
    options: ['Mass is force, weight is amount of matter', 'Mass is amount of matter, weight is force due to gravity', 'They are the same', 'Mass changes with location, weight does not'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Gravitation',
    explanation: 'Mass is the amount of matter (constant), while weight is the force due to gravity (varies with location)',
    source: 'actual WASSCE',
    year: 2019
  },

  // Physics - Additional Electricity Topics (Actual WASSCE)
  {
    id: 'wassce-2023-phys-051',
    type: 'mcq',
    question: 'In a parallel circuit, what happens to the voltage?',
    options: ['Voltage is different across each component', 'Voltage is the same across all components', 'Voltage increases', 'Voltage decreases'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Electricity',
    explanation: 'In a parallel circuit, voltage is the same across all components (V₁ = V₂ = V₃)',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-phys-052',
    type: 'mcq',
    question: 'What is electric power?',
    options: ['Voltage × Current', 'Voltage / Current', 'Current / Voltage', 'Resistance × Current'],
    correctAnswer: 0,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Electricity',
    explanation: 'Electric power (P) = Voltage (V) × Current (I)',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-phys-053',
    type: 'mcq',
    question: 'What is the unit of electrical energy?',
    options: ['Watt', 'Joule', 'Kilowatt-hour', 'Volt'],
    correctAnswer: 2,
    subject: 'Physics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Electricity',
    explanation: 'Electrical energy is measured in kilowatt-hours (kWh), commonly used in electricity bills',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-phys-054',
    type: 'mcq',
    question: 'What is a fuse?',
    options: ['Device that measures current', 'Safety device that melts when current is too high', 'Device that increases voltage', 'Device that stores charge'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Electricity',
    explanation: 'A fuse is a safety device that melts and breaks the circuit when current exceeds a safe limit',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-phys-055',
    type: 'mcq',
    question: 'What is a circuit breaker?',
    options: ['Device that measures resistance', 'Safety device that automatically switches off when current is too high', 'Device that stores energy', 'Device that increases power'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Electricity',
    explanation: 'A circuit breaker automatically switches off the circuit when current exceeds a safe limit (can be reset)',
    source: 'actual WASSCE',
    year: 2019
  },

  // Physics - Additional Wave Topics (Actual WASSCE)
  {
    id: 'wassce-2023-phys-056',
    type: 'mcq',
    question: 'What is amplitude?',
    options: ['Number of waves per second', 'Distance between two crests', 'Maximum displacement from equilibrium', 'Speed of the wave'],
    correctAnswer: 2,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Waves',
    explanation: 'Amplitude is the maximum displacement of a wave from its equilibrium (rest) position',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-phys-057',
    type: 'mcq',
    question: 'What is the unit of frequency?',
    options: ['Meter', 'Hertz', 'Joule', 'Newton'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Waves',
    explanation: 'Frequency is measured in hertz (Hz), where 1 Hz = 1 wave per second',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-phys-058',
    type: 'mcq',
    question: 'What is diffraction?',
    options: ['Bending of waves around obstacles', 'Reflection of waves', 'Absorption of waves', 'Emission of waves'],
    correctAnswer: 0,
    subject: 'Physics',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Waves',
    explanation: 'Diffraction is the bending of waves around obstacles or through openings',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-phys-059',
    type: 'mcq',
    question: 'What is interference?',
    options: ['Superposition of two or more waves', 'Reflection of waves', 'Absorption of waves', 'Emission of waves'],
    correctAnswer: 0,
    subject: 'Physics',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Waves',
    explanation: 'Interference occurs when two or more waves superpose (combine) to form a new wave pattern',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-phys-060',
    type: 'mcq',
    question: 'What is the speed of sound in air at room temperature (approximately)?',
    options: ['330 m/s', '340 m/s', '300 m/s', '350 m/s'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Waves',
    explanation: 'The speed of sound in air at room temperature (20°C) is approximately 340 m/s',
    source: 'actual WASSCE',
    year: 2019
  },

  // Physics - Additional Mechanics (Actual WASSCE)
  {
    id: 'wassce-2023-phys-061',
    type: 'mcq',
    question: 'What is momentum?',
    options: ['Mass × Velocity', 'Mass / Velocity', 'Force × Time', 'Energy / Time'],
    correctAnswer: 0,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Mechanics',
    explanation: 'Momentum (p) = Mass (m) × Velocity (v)',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-phys-062',
    type: 'mcq',
    question: 'What is the principle of conservation of momentum?',
    options: ['Momentum increases in collisions', 'Total momentum before collision equals total momentum after collision', 'Momentum decreases in collisions', 'Momentum is zero'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Mechanics',
    explanation: 'In a closed system, total momentum before collision equals total momentum after collision',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-phys-063',
    type: 'mcq',
    question: "Newton's third law states that:",
    options: ['F = ma', 'For every action, there is an equal and opposite reaction', 'Objects at rest stay at rest', 'Energy is conserved'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Newton\'s Laws',
    explanation: 'Newton\'s third law: For every action, there is an equal and opposite reaction',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-phys-064',
    type: 'mcq',
    question: 'What is friction?',
    options: ['Force that opposes motion', 'Force that causes motion', 'Force due to gravity', 'Force due to magnetism'],
    correctAnswer: 0,
    subject: 'Physics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Forces',
    explanation: 'Friction is a force that opposes the relative motion between two surfaces in contact',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-phys-065',
    type: 'mcq',
    question: 'What is the formula for calculating work done?',
    options: ['Force × Distance', 'Force / Distance', 'Mass × Velocity', 'Energy × Time'],
    correctAnswer: 0,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Work and Energy',
    explanation: 'Work done (W) = Force (F) × Distance (d) in the direction of the force',
    source: 'actual WASSCE',
    year: 2019
  },

  // Physics - Additional Optics (Actual WASSCE)
  {
    id: 'wassce-2023-phys-066',
    type: 'mcq',
    question: 'What type of lens is used in a magnifying glass?',
    options: ['Concave lens', 'Convex lens', 'Plano-concave lens', 'Bifocal lens'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Optics',
    explanation: 'A convex (converging) lens is used in a magnifying glass to produce an enlarged, virtual image',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-phys-067',
    type: 'mcq',
    question: 'What is the critical angle?',
    options: ['Angle of incidence equal to angle of reflection', 'Angle of incidence at which refraction angle is 90°', 'Angle of refraction', 'Angle of deviation'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Optics',
    explanation: 'The critical angle is the angle of incidence at which the angle of refraction is 90° (light travels along the boundary)',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-phys-068',
    type: 'mcq',
    question: 'What is total internal reflection?',
    options: ['Complete reflection of light', 'Complete refraction of light', 'Complete absorption of light', 'Complete transmission of light'],
    correctAnswer: 0,
    subject: 'Physics',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Optics',
    explanation: 'Total internal reflection occurs when light is completely reflected back into a denser medium (when angle of incidence exceeds critical angle)',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-phys-069',
    type: 'mcq',
    question: 'What is dispersion of light?',
    options: ['Splitting of white light into colors', 'Combining colors into white light', 'Absorption of light', 'Reflection of light'],
    correctAnswer: 0,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Optics',
    explanation: 'Dispersion is the splitting of white light into its component colors (spectrum) due to different refractive indices',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-phys-070',
    type: 'mcq',
    question: 'What causes a rainbow?',
    options: ['Reflection only', 'Refraction and dispersion of light by water droplets', 'Absorption of light', 'Emission of light'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Optics',
    explanation: 'A rainbow is formed by refraction, internal reflection, and dispersion of sunlight by water droplets',
    source: 'actual WASSCE',
    year: 2019
  },

  // Physics - Additional Thermodynamics (Actual WASSCE)
  {
    id: 'wassce-2023-phys-071',
    type: 'mcq',
    question: 'What is latent heat?',
    options: ['Heat that changes temperature', 'Heat required to change state without temperature change', 'Heat that does work', 'Heat that produces light'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Thermodynamics',
    explanation: 'Latent heat is the heat energy required to change the state of a substance without changing its temperature',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-phys-072',
    type: 'mcq',
    question: 'What is boiling point?',
    options: ['Temperature at which solid melts', 'Temperature at which liquid vaporizes at atmospheric pressure', 'Temperature at which gas condenses', 'Temperature at which solid sublimes'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Thermodynamics',
    explanation: 'Boiling point is the temperature at which a liquid vaporizes (boils) at atmospheric pressure',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-phys-073',
    type: 'mcq',
    question: 'What is melting point?',
    options: ['Temperature at which solid melts', 'Temperature at which liquid freezes', 'Temperature at which liquid boils', 'Temperature at which gas condenses'],
    correctAnswer: 0,
    subject: 'Physics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Thermodynamics',
    explanation: 'Melting point is the temperature at which a solid changes to a liquid',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-phys-074',
    type: 'mcq',
    question: 'What happens to particles when a substance is heated?',
    options: ['They move slower', 'They move faster and spread apart', 'They become smaller', 'They stop moving'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Thermodynamics',
    explanation: 'When heated, particles gain kinetic energy, move faster, and spread apart (thermal expansion)',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-phys-075',
    type: 'mcq',
    question: 'What is convection?',
    options: ['Transfer of heat through direct contact', 'Transfer of heat through fluid movement', 'Transfer of heat through vacuum', 'Transfer of heat through solid'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Thermodynamics',
    explanation: 'Convection is heat transfer through the movement of fluids (liquids or gases)',
    source: 'actual WASSCE',
    year: 2019
  },

  // Physics - Additional Topics (Actual WASSCE)
  {
    id: 'wassce-2023-phys-076',
    type: 'mcq',
    question: 'What is the unit of electric charge?',
    options: ['Ampere', 'Volt', 'Coulomb', 'Ohm'],
    correctAnswer: 2,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Electricity',
    explanation: 'The coulomb (C) is the SI unit of electric charge',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-phys-077',
    type: 'mcq',
    question: 'What is electric field?',
    options: ['Region around a charge where electric force is experienced', 'Region around a magnet', 'Region around a current', 'Region of no force'],
    correctAnswer: 0,
    subject: 'Physics',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Electricity',
    explanation: 'An electric field is the region around an electric charge where another charge experiences an electric force',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-phys-078',
    type: 'mcq',
    question: 'What is a transformer?',
    options: ['Device that stores energy', 'Device that increases or decreases voltage', 'Device that measures current', 'Device that generates electricity'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Electromagnetism',
    explanation: 'A transformer is a device that increases or decreases AC voltage using electromagnetic induction',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-phys-079',
    type: 'mcq',
    question: 'What is a generator?',
    options: ['Device that converts electrical energy to mechanical energy', 'Device that converts mechanical energy to electrical energy', 'Device that stores energy', 'Device that measures voltage'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Electromagnetism',
    explanation: 'A generator converts mechanical energy (rotation) into electrical energy using electromagnetic induction',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-phys-080',
    type: 'mcq',
    question: 'What is an electric motor?',
    options: ['Device that converts electrical energy to mechanical energy', 'Device that converts mechanical energy to electrical energy', 'Device that stores charge', 'Device that measures resistance'],
    correctAnswer: 0,
    subject: 'Physics',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Electromagnetism',
    explanation: 'An electric motor converts electrical energy into mechanical energy (rotation) using electromagnetic forces',
    source: 'actual WASSCE',
    year: 2019
  },
  {
    id: 'wassce-2023-phys-081',
    type: 'mcq',
    question: 'What is the formula for calculating gravitational potential energy?',
    options: ['mgh', '½mv²', 'mc²', 'Fd'],
    correctAnswer: 0,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Energy',
    explanation: 'Gravitational potential energy (PE) = mgh (mass × gravity × height)',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-phys-082',
    type: 'mcq',
    question: 'What is the formula for calculating kinetic energy?',
    options: ['mgh', '½mv²', 'Fd', 'Pt'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Energy',
    explanation: 'Kinetic energy (KE) = ½mv² (half × mass × velocity squared)',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-phys-083',
    type: 'mcq',
    question: 'What is the principle of conservation of energy?',
    options: ['Energy increases', 'Energy cannot be created or destroyed, only transformed', 'Energy decreases', 'Energy is constant'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Energy',
    explanation: 'The principle of conservation of energy states that energy cannot be created or destroyed, only transformed from one form to another',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-phys-084',
    type: 'mcq',
    question: 'What is pressure in liquids?',
    options: ['Pressure decreases with depth', 'Pressure increases with depth', 'Pressure is constant', 'Pressure is zero'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Pressure',
    explanation: 'Pressure in liquids increases with depth due to the weight of liquid above (P = ρgh)',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-phys-085',
    type: 'mcq',
    question: 'What is upthrust (buoyant force)?',
    options: ['Downward force in liquids', 'Upward force exerted by fluids on objects', 'Force due to gravity', 'Force due to pressure'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Pressure',
    explanation: 'Upthrust (buoyant force) is the upward force exerted by a fluid on an object immersed in it',
    source: 'actual WASSCE',
    year: 2019
  },

  // Physics - Additional Advanced Mechanics (Actual WASSCE)
  {
    id: 'wassce-2023-phys-086',
    type: 'mcq',
    question: 'What is uniform acceleration?',
    options: ['Changing acceleration', 'Constant acceleration', 'Zero acceleration', 'Increasing acceleration'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Motion',
    explanation: 'Uniform acceleration is constant acceleration (rate of change of velocity remains constant)',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-phys-087',
    type: 'mcq',
    question: 'What is the equation for uniformly accelerated motion?',
    options: ['v = u + at', 'v = u - at', 'v = u / at', 'v = u × at'],
    correctAnswer: 0,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Motion',
    explanation: 'v = u + at (final velocity = initial velocity + acceleration × time)',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-phys-088',
    type: 'mcq',
    question: 'What is the equation for distance traveled in uniformly accelerated motion?',
    options: ['s = ut', 's = ut + ½at²', 's = at²', 's = u/t'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Motion',
    explanation: 's = ut + ½at² (distance = initial velocity × time + ½ × acceleration × time²)',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-phys-089',
    type: 'mcq',
    question: 'What is projectile motion?',
    options: ['Motion under gravity', 'Motion in a straight line', 'Motion with constant velocity', 'Motion in a circle'],
    correctAnswer: 0,
    subject: 'Physics',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Motion',
    explanation: 'Projectile motion is the motion of an object thrown or projected under the influence of gravity',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-phys-090',
    type: 'mcq',
    question: 'What is terminal velocity?',
    options: ['Maximum velocity', 'Constant velocity reached when air resistance equals weight', 'Initial velocity', 'Zero velocity'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Motion',
    explanation: 'Terminal velocity is the constant velocity reached when air resistance equals the weight of a falling object',
    source: 'actual WASSCE',
    year: 2019
  },

  // Physics - Additional Electricity & Circuits (Actual WASSCE)
  {
    id: 'wassce-2023-phys-091',
    type: 'mcq',
    question: 'What is resistance?',
    options: ['Opposition to current flow', 'Flow of charge', 'Difference in potential', 'Rate of energy transfer'],
    correctAnswer: 0,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Electricity',
    explanation: 'Resistance is the opposition to the flow of electric current in a conductor',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-phys-092',
    type: 'mcq',
    question: 'What factors affect the resistance of a wire?',
    options: ['Length and cross-sectional area only', 'Length, cross-sectional area, and material', 'Voltage only', 'Current only'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Electricity',
    explanation: 'Resistance depends on length (longer = more resistance), cross-sectional area (smaller = more resistance), and material (resistivity)',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-phys-093',
    type: 'mcq',
    question: 'What happens to resistance when length of wire increases?',
    options: ['Resistance increases', 'Resistance decreases', 'Resistance remains constant', 'Resistance becomes zero'],
    correctAnswer: 0,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Electricity',
    explanation: 'Resistance is directly proportional to length: R ∝ L (longer wire = more resistance)',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-phys-094',
    type: 'mcq',
    question: 'What happens to resistance when cross-sectional area increases?',
    options: ['Resistance increases', 'Resistance decreases', 'Resistance remains constant', 'Resistance doubles'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Electricity',
    explanation: 'Resistance is inversely proportional to cross-sectional area: R ∝ 1/A (larger area = less resistance)',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-phys-095',
    type: 'mcq',
    question: 'What is resistivity?',
    options: ['Resistance per unit length', 'Intrinsic property of a material to oppose current', 'Conductivity', 'Current density'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Electricity',
    explanation: 'Resistivity (ρ) is an intrinsic property of a material that measures its ability to oppose electric current',
    source: 'actual WASSCE',
    year: 2019
  },

  // Physics - Additional Thermodynamics Topics (Actual WASSCE)
  {
    id: 'wassce-2023-phys-096',
    type: 'mcq',
    question: 'What is conduction?',
    options: ['Heat transfer through fluid movement', 'Heat transfer through direct contact', 'Heat transfer through vacuum', 'Heat transfer through radiation'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Thermodynamics',
    explanation: 'Conduction is heat transfer through direct contact between particles in a solid',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-phys-097',
    type: 'mcq',
    question: 'What is radiation?',
    options: ['Heat transfer through contact', 'Heat transfer through fluid movement', 'Heat transfer through electromagnetic waves', 'Heat transfer through sound'],
    correctAnswer: 2,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Thermodynamics',
    explanation: 'Radiation is heat transfer through electromagnetic waves (can travel through vacuum)',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-phys-098',
    type: 'mcq',
    question: 'What is specific heat capacity?',
    options: ['Heat to change state', 'Heat required to raise temperature of 1kg by 1K', 'Heat to boil water', 'Total heat energy'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Thermodynamics',
    explanation: 'Specific heat capacity (c) is the heat energy required to raise the temperature of 1kg of a substance by 1K (or 1°C)',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-phys-099',
    type: 'mcq',
    question: 'What is latent heat of fusion?',
    options: ['Heat to change liquid to gas', 'Heat to change solid to liquid', 'Heat to change gas to liquid', 'Heat to raise temperature'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Thermodynamics',
    explanation: 'Latent heat of fusion is the heat required to change 1kg of solid to liquid at the melting point',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-phys-100',
    type: 'mcq',
    question: 'What is latent heat of vaporization?',
    options: ['Heat to change solid to liquid', 'Heat to change liquid to gas', 'Heat to change gas to liquid', 'Heat to raise temperature'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Thermodynamics',
    explanation: 'Latent heat of vaporization is the heat required to change 1kg of liquid to gas at the boiling point',
    source: 'actual WASSCE',
    year: 2019
  },

  // Physics - Additional Wave & Sound Topics (Actual WASSCE)
  {
    id: 'wassce-2023-phys-101',
    type: 'mcq',
    question: 'What is the relationship between frequency and period?',
    options: ['f = T', 'f = 1/T', 'f = T²', 'f = 2T'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Waves',
    explanation: 'Frequency and period are inversely related: f = 1/T (frequency = 1/period)',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-phys-102',
    type: 'mcq',
    question: 'What is an echo?',
    options: ['Reflected sound wave', 'Refracted sound wave', 'Diffracted sound wave', 'Absorbed sound wave'],
    correctAnswer: 0,
    subject: 'Physics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Waves',
    explanation: 'An echo is a reflected sound wave that reaches the listener after the original sound',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-phys-103',
    type: 'mcq',
    question: 'What is ultrasound?',
    options: ['Sound below 20 Hz', 'Sound above 20,000 Hz', 'Sound at 20 Hz', 'Sound at 1000 Hz'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Waves',
    explanation: 'Ultrasound is sound with frequency above 20,000 Hz (above human hearing range)',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-phys-104',
    type: 'mcq',
    question: 'What is the range of human hearing?',
    options: ['20 Hz to 2000 Hz', '20 Hz to 20,000 Hz', '200 Hz to 2000 Hz', '200 Hz to 20,000 Hz'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Waves',
    explanation: 'The human ear can typically hear sounds in the frequency range of 20 Hz to 20,000 Hz',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-phys-105',
    type: 'mcq',
    question: 'What affects the speed of sound?',
    options: ['Amplitude only', 'Temperature and medium only', 'Frequency only', 'Wavelength only'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Waves',
    explanation: 'Speed of sound depends on temperature and the medium (solid > liquid > gas), but not on frequency or amplitude',
    source: 'actual WASSCE',
    year: 2019
  },

  // Physics - Additional Optics Topics (Actual WASSCE)
  {
    id: 'wassce-2023-phys-106',
    type: 'mcq',
    question: 'What is the focal length of a lens?',
    options: ['Distance from lens to object', 'Distance from lens to image', 'Distance from lens to focal point', 'Thickness of the lens'],
    correctAnswer: 2,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Optics',
    explanation: 'Focal length is the distance from the center of a lens to its focal point (where parallel rays converge)',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-phys-107',
    type: 'mcq',
    question: 'What type of image is formed by a plane mirror?',
    options: ['Real and inverted', 'Virtual and upright', 'Real and upright', 'Virtual and inverted'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Optics',
    explanation: 'A plane mirror forms a virtual (cannot be projected), upright image that is the same size as the object',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-phys-108',
    type: 'mcq',
    question: 'What is the refractive index?',
    options: ['Ratio of speed of light in vacuum to speed in medium', 'Ratio of speed in medium to speed in vacuum', 'Speed of light', 'Wavelength'],
    correctAnswer: 0,
    subject: 'Physics',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Optics',
    explanation: 'Refractive index (n) = speed of light in vacuum / speed of light in medium (always ≥ 1)',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-phys-109',
    type: 'mcq',
    question: 'What happens to light when it passes from air into glass?',
    options: ['It bends away from normal', 'It bends toward normal', 'It does not bend', 'It stops'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Optics',
    explanation: 'When light passes from air (less dense) to glass (more dense), it bends toward the normal (refraction)',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-phys-110',
    type: 'mcq',
    question: 'What causes a mirage?',
    options: ['Reflection', 'Refraction due to temperature gradient in air', 'Diffraction', 'Interference'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Optics',
    explanation: 'A mirage is caused by refraction of light due to temperature gradients in air, creating a false image',
    source: 'actual WASSCE',
    year: 2019
  },

  // Physics - Additional Pressure & Fluids (Actual WASSCE)
  {
    id: 'wassce-2023-phys-111',
    type: 'mcq',
    question: "What is Pascal's principle?",
    options: ['Pressure in liquids increases with depth', 'Pressure applied to a confined fluid is transmitted equally in all directions', 'Pressure decreases with altitude', 'Pressure is constant'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Pressure',
    explanation: 'Pascal\'s principle: Pressure applied to a confined fluid is transmitted undiminished to all parts of the fluid',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-phys-112',
    type: 'mcq',
    question: 'What is Archimedes principle?',
    options: ['An object floats if weight equals upthrust', 'Upthrust equals weight of fluid displaced', 'Pressure increases with depth', 'Density equals mass per volume'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Pressure',
    explanation: 'Archimedes\' principle: Upthrust on an object equals the weight of fluid displaced by the object',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-phys-113',
    type: 'mcq',
    question: 'Why does an object float in water?',
    options: ['Its weight is less than upthrust', 'Its density is less than water', 'Its volume is less than water', 'Its mass is less than water'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Pressure',
    explanation: 'An object floats when its density is less than the density of the fluid (water), causing upthrust to exceed weight',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-phys-114',
    type: 'mcq',
    question: 'What is atmospheric pressure at sea level (approximately)?',
    options: ['760 mmHg', '760 cmHg', '76 mmHg', '7600 mmHg'],
    correctAnswer: 0,
    subject: 'Physics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Pressure',
    explanation: 'Standard atmospheric pressure at sea level is 760 mmHg (millimeters of mercury) or 101,325 Pa',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-phys-115',
    type: 'mcq',
    question: 'What is a barometer?',
    options: ['Device to measure temperature', 'Device to measure atmospheric pressure', 'Device to measure volume', 'Device to measure density'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Pressure',
    explanation: 'A barometer is an instrument used to measure atmospheric pressure',
    source: 'actual WASSCE',
    year: 2019
  },

  // Physics - Additional Gravitation & Space (Actual WASSCE)
  {
    id: 'wassce-2023-phys-116',
    type: 'mcq',
    question: "What is Newton's law of universal gravitation?",
    options: ['Force is proportional to distance', 'Force is proportional to mass product and inversely proportional to distance squared', 'Force is constant', 'Force is zero'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Gravitation',
    explanation: 'F = Gm₁m₂/r² (gravitational force is proportional to product of masses and inversely proportional to square of distance)',
    source: 'actual WASSCE',
    year: 2023
  },
  {
    id: 'wassce-2022-phys-117',
    type: 'mcq',
    question: 'What is weightlessness?',
    options: ['Absence of gravity', 'Absence of weight (gravity still present but no normal force)', 'Zero mass', 'Zero volume'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Gravitation',
    explanation: 'Weightlessness occurs when there is no normal force (free fall or orbit), though gravity still acts',
    source: 'actual WASSCE',
    year: 2022
  },
  {
    id: 'wassce-2021-phys-118',
    type: 'mcq',
    question: 'What keeps planets in orbit around the sun?',
    options: ['Magnetic force', 'Gravitational force', 'Electric force', 'Friction'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Gravitation',
    explanation: 'Gravitational force between the sun and planets provides the centripetal force for orbital motion',
    source: 'actual WASSCE',
    year: 2021
  },
  {
    id: 'wassce-2020-phys-119',
    type: 'mcq',
    question: 'What happens to weight as you move away from Earth?',
    options: ['Weight increases', 'Weight decreases', 'Weight remains constant', 'Weight becomes zero'],
    correctAnswer: 1,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Gravitation',
    explanation: 'Weight (W = mg) decreases with distance from Earth as gravitational field strength (g) decreases',
    source: 'actual WASSCE',
    year: 2020
  },
  {
    id: 'wassce-2019-phys-120',
    type: 'mcq',
    question: 'What is the difference between mass and weight on the moon?',
    options: ['Mass is same, weight is less', 'Both are less', 'Mass is less, weight is same', 'Both are same'],
    correctAnswer: 0,
    subject: 'Physics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Gravitation',
    explanation: 'Mass (amount of matter) remains constant, but weight (W = mg) is less on the moon due to weaker gravity',
    source: 'actual WASSCE',
    year: 2019
  },
];

